### ISSUE TITLE
Typing is lagging when all linters are enabled

### ISSUE THREAD

**Issue by Sergey1011010** [xxpxxxxp/intellij-plugin-golangci-lint#10]
You probably need to do linting in another thread, because now linting causes lagging for typing.

**Comment by xxpxxxxp** [comment]
Thanks @Sergey1011010 , I'm aware the linter is causing running slow when editing, I'm trying to make it run only on files saved, hope that would solve the problem.

**Comment by xxpxxxxp** [comment]
@Sergey1011010  Please check if the lagging issue still exist on v1.2.6.

**Comment by Sergey1011010** [comment]
@xxpxxxxp, yep, now it works, thanks. I'm closing the issue.
