### ISSUE TITLE
Why so slow?

### ISSUE THREAD

**Issue by frederikhors** [xxpxxxxp/intellij-plugin-golangci-lint#101]
Why if I run `golangci-lint run` in my root directory it ends in 2 seconds and instead in Goland with inspection tool it ends after 2/3 minutes or more?

![image](https://user-images.githubusercontent.com/41120635/152654396-b9c96a6b-c061-4b0e-ac98-98061f8f8a53.png)

![image](https://user-images.githubusercontent.com/41120635/152654461-e794bb7e-b4cb-4d5a-9222-fcf1cdacf1a4.png)

**Comment by xxpxxxxp** [comment]
Please don't use whole project scope if you got a big project, the plugin is running per file, so by whole project, Goland will enumerate all files and call the plugin sequently. While manually run golangci-lint on root dir is one pass, it's certainly much much quicker.

**Comment by frederikhors** [comment]
And this is a problem because I have installed Go-linter just for the global inspection which lists the problems in the whole project and it is very convenient because clicking takes me there and I can fix the problems.

If I have to use the terminal it doesn't make much sense to have Go-linter. No?

**Comment by xxpxxxxp** [comment]
Yeah, I understand your use case. The plugin is mainly for the purpose of viewing issues in the editor, so that we can fix code inline, that's why it been designed to run per file, this mode sure doesn't work well with a large score.

**Comment by frederikhors** [comment]
Is there a way to change it to work well with global inspection? Should we ask for help on jetbrains issues platform?
