### ISSUE TITLE
How to get permission from macbook apple m1

### ISSUE THREAD

**Issue by songkane** [xxpxxxxp/intellij-plugin-golangci-lint#105]
I don't know if  this is the reason
it occurs in a new macbook m1 
it's ok for my old macbook with intel

<img width="787" alt="image" src="https://user-images.githubusercontent.com/15307785/161377481-cbb9d18d-c993-4a19-9f30-6bed1c4325bb.png">

**Comment by xxpxxxxp** [comment]
Hi @songkane , it means the current Goland instance, where the plugin resides, doesn't have permission to write `/usr/local/bin`. The permission of this folder may vary between systems. `Get Latest` button also has a pop-up to let you choose a location, choose a proper directory then to avoid this failure.
