### ISSUE TITLE
Support linter binary inside WSL

### ISSUE THREAD

**Issue by krikun98** [xxpxxxxp/intellij-plugin-golangci-lint#106]
A development environment inside WSL is a common thing, and the plugin does not let you select the golangci-lint binary in the Linux filesystem in GoLand. I'm constantly getting the following error with the path pointing to the `.exe` Windows binary:
```
Go linter running error
Please make sure no syntax or config error, then run 'go mod tidy' to make sure deps ok
```

**Comment by krikun98** [comment]
Checked closed issues - running the command via `wsl -d ubuntu path_to_home/go/bin/golangci-lint --version` in Powershell gives the following error:
```
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
        github.com/go-critic/go-critic@v0.6.2/checkers/embedded_rules.go:46 +0x4b4
```
I had the same errors happen when I was installing the wrong version of `golangci-lint` for my Go version. It's probably not picking up the language files.

**Comment by xxpxxxxp** [comment]
Working on it

**Comment by dowglaz** [comment]
Hi! I opened an issue on GoLand's tracker and they redirected me to this plugin repo. I'll send here the text I sent there:

> I identified two bugs:
>
> 1. When I try to set up golangci-lint to "run on save", it just downloads the native windows executable "golangci-lint.exe" file (when I click on "Get latest") and it doesn't allow me to select a WSL (Linux) native executable. I'm not sure if it's related to the ".exe" being used instead of a Linux executable, but no lint errors are shown on my IDE (and there are lint errors that I can confirm by calling it from the terminal).
> When I save a file, it always pops up a message saying there were errors with the golangci-linter.
> 
> 2. Because of that, I tried to disable it completely so it stops showing me errors all the time. But I can't! Because when I *disable all* the linters, it just *enables all* of them. Clearly, there's a bug here on the data handling.
> 

I'm not sure if it's related with this issue you guys are discussing here, but let me know if I need to open another one instead.

**Comment by xxpxxxxp** [comment]
@dowglaz The plugin doesn't work with WSL now, I'm working on the support.

**Comment by Rigellute** [comment]
Would love for this plugin to work within WSL!

**Comment by AndresXLP** [comment]
> @dowglaz The plugin doesn't work with WSL now, I'm working on the support.

there is no support for WSL yet right?

**Comment by xxpxxxxp** [comment]
@AndresXLP I've made it work, going to release soon

**Comment by xxpxxxxp** [comment]
WLS is supported in the new version, please try out

**Comment by AndresXLP** [comment]
> WLS is supported in the new version, please try out

is the new version available?

![image](https://user-images.githubusercontent.com/92891655/204306192-6e3e990d-0957-4540-9873-18ee1849fc8d.png)

**Comment by xxpxxxxp** [comment]
@AndresXLP sorry the new version still pending Jetbrains's approval, expect to available tmr or at most 2 days after.

**Comment by xxpxxxxp** [comment]
Hi all, as WSL is officially supported within plugin, I'm closing this ticket now. Feel free to open other topics about usage issues.

**Comment by AndresXLP** [comment]
> @AndresXLP sorry the new version still pending Jetbrains's approval, expect to available tmr or at most 2 days after.

![image](https://user-images.githubusercontent.com/92891655/204332416-bfb126e6-bd0d-4a72-8007-9082e4a0c67c.png)

You're the best

**Comment by Rigellute** [comment]
Great, thank you @xxpxxxxp!

**Comment by asaf92** [comment]
I can't select the golangci-lint executable in WSL. Any idea why?

I'm using the latest version of the plugin (1.6.2).

![image](https://user-images.githubusercontent.com/35231408/205042660-80f94e11-c32e-44e3-be43-22946c4e9631.png)
![image](https://user-images.githubusercontent.com/35231408/205042836-9b7aca15-9aa5-4326-a8b2-674693b81eda.png)
