### ISSUE TITLE
golangci-lint  1.47.1 version not recognized

### ISSUE THREAD

**Issue by Lvzhenqian** [xxpxxxxp/intellij-plugin-golangci-lint#114]
as shown like this:
![截图_选择区域_20220721154541](https://user-images.githubusercontent.com/17487028/180159244-ab021ea4-ed4f-4095-b707-30ee8797e33e.png)

**Comment by xxpxxxxp** [comment]
Hi @Lvzhenqian , it's possible that due to v1.47.1 being much slower, it timeout then the plugin thought it was not compatible. Would you please try with v1.47.2 https://github.com/golangci/golangci-lint/releases/tag/v1.47.2
