### ISSUE TITLE
multiple projects and specific `Project Root` for each project

### ISSUE THREAD

**Issue by jerome-laforge** [xxpxxxxp/intellij-plugin-golangci-lint#115]
It is not possible to define for each intellij project their own `Project Root`that is contained .golangci config file (each project has own golangci config file). If I modify the `Project Root` for one Go projet, all other Go project has the same.

**Comment by xxpxxxxp** [comment]
Sorry, I didn't get what your means, would a per-intellij instance config solve your issue?

**Comment by jerome-laforge** [comment]
Sorry if I was not enough clear.

I have two projects (or more) within intellij.
For example:
```
- /home/user/myProject1/ (.idea is in this directory)
                                     ./src/ (.golangci.yml for this project is in this directory)
- /home/user/myProject2/ (.idea is in directory)
                                     ./src/ (.golangci.yml for this project is in this directory)
```

the .golangci.yml from myProject1 is not the same of myProject2.

For myProject1, if you configure the plugin golangci-lint for pointing to `/home/user/myProject1/src` that will affect also config for myProject2.

![debug](https://user-images.githubusercontent.com/9979375/180740426-7b3bd90f-d19a-45cd-b964-d94d1ce229e0.png)

**Comment by xxpxxxxp** [comment]
Ah got it. So basically a project-based config should solve the problem, right? I'm working on such change, ETA 2 weeks, sorry for the inconvenience.

**Comment by jerome-laforge** [comment]
> a project-based config should solve the problem, right? 

yes, it is.

**Comment by xxpxxxxp** [comment]
Per project config is supported in latest release.

**Comment by jerome-laforge** [comment]
It works like a charm.
