### ISSUE TITLE
Not able to select config file

### ISSUE THREAD

**Issue by Roshan-Mehta1** [xxpxxxxp/intellij-plugin-golangci-lint#117]
I want to change the config file for golangci-lint. But currently there is no option to change the config file path. It is automatically detecting the path. 
<img width="977" alt="Screenshot 2022-08-05 at 9 42 39 AM" src="https://user-images.githubusercontent.com/105209272/183000096-be844d14-3474-48c6-8760-0358d4c78591.png">

**Comment by xxpxxxxp** [comment]
Hi @Roshan-Mehta1 , could you explain more about the use case? Cause mostly people would want to use the `.golangci.yml` under the project root, to be aligned with the CI system. If you are not using a CI system, then you are free to change your own `.golangci.yml` to staisfy your need.

**Comment by juan-alvarez-sp** [comment]
@xxpxxxxp in my case, I have a `.golangci.yml` at `$HOME`, which is my default
