### ISSUE TITLE
Path setting across all projects

### ISSUE THREAD

**Issue by huyz** [xxpxxxxp/intellij-plugin-golangci-lint#127]
Every time I open a new project, the plugin asks me to set the path for `golangci-lint`.

Can the setting be remembered and shared for all projects?

**Comment by xxpxxxxp** [comment]
Hi @huyz , sorry for that, I know it is frustrating, some people want different configurations per project (eg. #109 #115), so this 1-time pop-up is useful in such cases.

**Comment by huyz** [comment]
Is it possible to have the path for `.golangci.yml` be per-project while the path for `golangci-lint` be across all projects?  That would satisfy everyone I think

**Comment by huyz** [comment]
Or maybe copy the per-project path `golangci-lint` to an across-projects default setting. Then whenever a new project is encountered, the across-projects default setting can be copied to the per-project path for this new project

**Comment by xxpxxxxp** [comment]
Good idea, the plugin can skip setup if
* there's golangci-lint exe in PATH
* there's .golangci.yml config for current project

Otherwise, it would be better for user config the plugin for 1 time, as default linters are far from good for most cases.

**Comment by dekimsey** [comment]
> there's golangci-lint exe in PATH

Was this implemented? I see the discussion about the changed occurred after the issue was closed. In my case the binary is in my PATH but it prompting on every load.

GoLand 2022.2.5
Go Linter 1.6.3

Thank you!

**Comment by xxpxxxxp** [comment]
@dekimsey sryI totally forgot this, doing now

**Comment by xxpxxxxp** [comment]
done, open a new project that has .golangci.yml under its path and a golangci-lint executable under $PATH will not show pop-up.

**Comment by huyz** [comment]
Thank you!
