### ISSUE TITLE
使用过程中报错

### ISSUE THREAD

**Issue by ywanbing** [xxpxxxxp/intellij-plugin-golangci-lint#128]
go-linter：1.6.1
goland: 2022.1.3
go: 1.17.3
golangci-lint: 1.50.1

![image](https://user-images.githubusercontent.com/30226135/199940225-5c4bd9f9-bdb6-4171-8059-ba2356f4ae2b.png)

代码都没有问题，但是插件会报错

开启的插件如下：
![image](https://user-images.githubusercontent.com/30226135/199940456-850bed09-7b28-4465-b757-c585168538ea.png)

我想知道插件 `go-linter` 的运行原理； 他在修改文件的时候，好像只检查了当前文件。

只检查改动文件，这种情况下有的文件引用其他没有选中的文件的内容，他就会报错。

**Comment by xxpxxxxp** [comment]
Hi @ywanbing , 麻烦找一下log，在菜单里选 `帮助 - Show Log in xxx`
在log里搜索 `go-linter` 相关的几条贴这里就行。

插件针对单个文件运行时候，是定位到文件的当前目录，然后执行 `golangci-lint` ，没改动的文件也可以正常引用的。可能是一些conf上的问题，看一下log就清楚了。

<img width="406" alt="image" src="https://user-images.githubusercontent.com/1585918/199950301-33f30560-4958-4dfa-944a-23fece9b547c.png">

**Comment by ywanbing** [comment]
![image](https://user-images.githubusercontent.com/30226135/199952603-9a8c06a3-fa82-40e2-bc31-75bfda55931e.png)
就像是在检查指定文件，没有读取其他文件的内容，导致的这种错误

**Comment by ywanbing** [comment]
![image](https://user-images.githubusercontent.com/30226135/199953988-919e0b1e-2956-44af-a3b8-9660bdf09959.png)

我测试了一下你说的情况，在目录下运行它不会出现问题；但是指定文件运行，就会出现和我日志报错的情况。

**Comment by xxpxxxxp** [comment]
Hi @ywanbing , golangci-lint 不支持跑单个文件，只能针对目录跑。
看log里的错误，可以先看看 `go build` 能不能顺利通过，error看起来是招不到某个package， build更新一下go.mod应该就可以了

**Comment by ywanbing** [comment]
> Hi @ywanbing , golangci-lint 不支持跑单个文件，只能针对目录跑。 看log里的错误，可以先看看 `go build` 能不能顺利通过，error看起来是招不到某个package， build更新一下go.mod应该就可以了

go build 可以通过，是否可以检查一下，它（插件）使用了单个文件检查？

**Comment by xxpxxxxp** [comment]
不会的，plugin只会针对某个folder跑
试试这样跑 `cd autogroupserver/src/world && golangci-lint.exe run -c ../../../.golangci.yml .`

**Comment by ywanbing** [comment]
![image](https://user-images.githubusercontent.com/30226135/200548100-eb80b5a9-4a29-4854-a6b3-1969f36f55fc.png)
这样跑没有问题

**Comment by xxpxxxxp** [comment]
在 `autogroupserver/src/world` 这个目录下试试，就是上面log里显示出错的目录

**Comment by ywanbing** [comment]
我发现了命令 
![image](https://user-images.githubusercontent.com/30226135/203258107-93de80c4-ae60-471c-a897-6ca7755ce3b7.png)
我复制下来跑，是正确的； 但是在goland里面却是报错。

**Comment by xxpxxxxp** [comment]
之前log的 `Debug command` 确实有问题，已经更新添加了 ""
这个 Debug command 就是 plugin 跑的方式，如果 Goland 里总是不行，但 Debug command 拷出来就能跑成功，是不是cmd里有一些特殊的环境变量？比如 GOPRIVATE 这种

**Comment by ywanbing** [comment]
我通过以下操作解决了我的问题

``` shell
$ go clean -modcache
$ go mod tidy
```
