### ISSUE TITLE
Wrong arch detected on Macbook M1

### ISSUE THREAD

**Issue by ptxmac** [xxpxxxxp/intellij-plugin-golangci-lint#129]
Even though I'm running the arm version of intellij and have installed the arm version of golangci-lint this plugin tries to set the build-tags to amd64:

```
2022-11-18 12:25:43,712 [ 653891]   WARN - go-linter - Debug command: cd <REDACTED>
 && export PATH=/usr/local/go/bin:/usr/bin:/bin:/usr/sbin:/sbin 
&& export GOPATH= 
&& export GO111MODULE=on 
&& '/opt/homebrew/Cellar/golangci-lint/1.50.1/bin/golangci-lint' 'run'
 '--out-format' 'json' '--allow-parallel-runners' 
'-j' '2' '--issues-exit-code' '1' '--max-issues-per-linter' '0'
 '--max-same-issues' '0' '-c' '/<REDACTED>/.golangci.yaml' '--build-tags' 'amd64' '.'
```

Running `arch` in intellij's terminal returns `arm64`.

And my own settings for build-tags is set to arm
![image](https://user-images.githubusercontent.com/56919/202696006-28e14233-b20f-438f-8792-4ebe734ad0bd.png)

It looks like this code is responsible for detecting the architecture: https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/blob/master/src/main/kotlin/com/ypwang/plugin/platform/Platform.kt#L57

**Comment by xxpxxxxp** [comment]
sorry don't get what happened, hope your issue resolved, and do feel free to reopen if something go wrong.

**Comment by ptxmac** [comment]
You can see my mistake in the history of the issue 😄
