### ISSUE TITLE
Go linter running error , Please make sure no syntax or config error, then run 'go mod tidy' to ensure deps ok

### ISSUE THREAD

**Issue by fynntang** [xxpxxxxp/intellij-plugin-golangci-lint#133]
> Please make sure no syntax or config error, then run 'go mod tidy' to ensure deps ok

![](https://files.catbox.moe/h5k1yp.png)

**Comment by fynntang** [comment]
More

After I executed the `go mod tidy` command, I still reported the same error. I also tried to restart my GoLand application and restart the mac system

![](https://files.catbox.moe/mqcpxl.png)

**Comment by xxpxxxxp** [comment]
Hi @fynntang , could you paste the debug command here too, you can find it by `Help - Show Log in Finder - Open the log and search "go-linter"`

**Comment by fynntang** [comment]
Hi @xxpxxxxp , The following contents are logs, where I replaced my project directory and package name


```
2023-01-30 23:41:07,499 [28964509]   WARN - go-linter - Run error: level=warning msg="[runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'."
level=warning msg="[runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. "
level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package biz: could not load export data: no export data for \"github.com/<OrganizationName>/<ProjectName>/internal/wallet/biz\""
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package biz: could not load export data: no export data for \"github.com/<OrganizationName>/<ProjectName>/internal/wallet/biz\"\n\n"
. Please make sure the project has no syntax error.
2023-01-30 23:41:07,499 [28964509]   WARN - go-linter - Debug command: cd '<ProjectDir>' && export PATH='/usr/local/go/bin:/usr/bin:/bin:/usr/sbin:/sbin' && export GOPATH='' && export GO111MODULE='on' && '/Users/<username>/go/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '2' '--issues-exit-code' '1' '--max-issues-per-linter' '0' '--max-same-issues' '0' '--no-config' '--disable-all' '-E' 'exportloopref,staticcheck,interfacer,govet,dupl,errorlint,funlen,gocritic,goconst,gocognit,ineffassign,bodyclose,gosec,maligned,stylecheck,revive,whitespace,goprintffuncname,gosimple,prealloc,gocyclo' 'pkg/task/tasks'
2023-01-30 23:41:13,782 [28970792]   WARN - go-linter - Run error: level=warning msg="[runner] The linter 'maligned' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'."
level=warning msg="[runner] The linter 'interfacer' is deprecated (since v1.38.0) due to: The repository of the linter has been archived by the owner. "
level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package biz: could not load export data: no export data for \"github.com/<OrganizationName>/<ProjectName>/internal/wallet/biz\""
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package biz: could not load export data: no export data for \"github.com/<OrganizationName>/<ProjectName>/internal/wallet/biz\"\n\n"
. Please make sure the project has no syntax error.
```

**Comment by xxpxxxxp** [comment]
Thanks, would you execute the debug command, see if it success?
From the command I see `GOPATH` is empty, would you also attach your IDE's GOPATH settings, like this
<img width="977" alt="image" src="https://user-images.githubusercontent.com/1585918/215641067-35cf6c55-dc62-4281-9233-4691f3c1ad54.png">

**Comment by fynntang** [comment]
Hi @xxpxxxxp Thanks, 

![](https://files.catbox.moe/kcrs5h.png)
![](https://files.catbox.moe/hv6f8a.png)
![](https://files.catbox.moe/1decsv.png)

**Comment by xxpxxxxp** [comment]
thanks, config seems fine, would you execute the debug command to see if it success?

**Comment by fynntang** [comment]
Hey, @xxpxxxxp thanks,

I can use `golangci-lint run` to run normally.  I can't execute the debug command. Can you teach me

![](https://files.catbox.moe/zwckq5.png)

**Comment by xxpxxxxp** [comment]
Ah it's the debug command printed by the plugin to log, it's what the plugin trying to do:
```2023-01-30 23:41:07,499 [28964509]   WARN - go-linter - Debug command: cd '<ProjectDir>' && export PATH='/usr/local/go/bin:/usr/bin:/bin:/usr/sbin:/sbin' && export GOPATH='' && export GO111MODULE='on' && '/Users/<username>/go/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '2' '--issues-exit-code' '1' '--max-issues-per-linter' '0' '--max-same-issues' '0' '--no-config' '--disable-all' '-E' 'exportloopref,staticcheck,interfacer,govet,dupl,errorlint,funlen,gocritic,goconst,gocognit,ineffassign,bodyclose,gosec,maligned,stylecheck,revive,whitespace,goprintffuncname,gosimple,prealloc,gocyclo' 'pkg/task/tasks'```

Please execute and see output. If it fails, would you fill in the part `export GOPATH=''` with your actually GOPATH and re-execute again, I'm suspecting GOPATH missing caused the problem.

**Comment by fynntang** [comment]
Thank you very much. After I added the `GOPATH` variable in the `.zshrc` file, it will be normal

![](https://files.catbox.moe/i77lx0.png)
