### ISSUE TITLE
Add environment variables config

### ISSUE THREAD

**Issue by Kennnnnnji** [xxpxxxxp/intellij-plugin-golangci-lint#136]
For example, sometimes it needs `GOARCH=amd64` to build a project on a M1 Macbook. 

If this tool can configure that, it can work in such case.

**Comment by Kennnnnnji** [comment]
the ultimate cmd can be like : `GOARCH=amd64 golangci-lint run $file`

**Comment by xxpxxxxp** [comment]
Hi @Kennnnnnji , if I understand correctly, you are trying to cross build from M1 to amd64 target.
The plugin takes OS/Arch settings from Go config, you can set the arch to amd64 in `Build Tags & Vendoring` section of Go config, then the linter will run target amd64 too.

![image](https://user-images.githubusercontent.com/1585918/225366765-97490181-2c31-4955-be97-f5dd695e49be.png)

**Comment by Kennnnnnji** [comment]
@xxpxxxxp Awesome, thanks!
