### ISSUE TITLE
Use golangci-linter compatible or importable format

### ISSUE THREAD

**Issue by Marakai** [xxpxxxxp/intellij-plugin-golangci-lint#137]
Hi! Thanks for replying to my message on the Jetbrains forum page for you plugin.

What I meant by is that that while the file you store the plugin configuration in (`golinter.xml` in `.../.idea`) uses XML, `golangci-linter` uses a YAML configuration file.

In that file the activated linters are stored in the
```
linters:
 - gosec
 - goerr113
 - ...
```
section.

It would be grat for your Goland plugin to have an import and export function, where I can point it to a `golangci-linter` YAML config file and it read from the `linters:` section to set the active ones - but even better would allow me to write the settings into that YAML file!

**Comment by xxpxxxxp** [comment]
Hi @Marakai , if your project has a `.golangci.yml` config file, the plugin config panel will show it, and disable linter selection.
The plugin's config file `.idea/golinter.xml` does store a copy of enabled linters from `.golangci.yml`, while actually that doesn't take effect, the plugin is using the config instead.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/1585918/229574197-d52b6640-1601-42ba-8115-1f1a31aca534.png">
