### ISSUE TITLE
Golang linter issue: 'running `go list all`: exit status 1'

### ISSUE THREAD

**Issue by dliakhov** [xxpxxxxp/intellij-plugin-golangci-lint#139]
I'm facing error while running the Go Linter tool downloaded as a plugin from the market place, in my IntelliJ IDEA IDE. The following are the details around the scenario for your reference.

Environment
- Platform: MacOS 13.2
- IDE: IntelliJ IDEA 2023.1
- Go Linter: 1.52.2
- Go version: 1.19.2

When I installed Go linter it can't run the linter, in the logs it shows next error:

```
2023-04-18 18:18:03,037 [372874826]   WARN - go-linter - Run error: level=warning msg="[runner] Can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1"
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1\n\n"
. Please make sure the project has no syntax error.
```

And on UI I can see this pop up

<img width="377" alt="image" src="https://user-images.githubusercontent.com/8529665/232829649-fa80fcfb-0999-456d-a87d-66c8d23bdea2.png">

I've tried to run `go mod tidy` and it nothing changed.

Also I've tried to run `go list all` in console and it didn't return an error.

**Comment by xxpxxxxp** [comment]
Hi @dliakhov , please search the log with `Debug command:`, and execute the debug command in your terminal, to see if the command could run successfully.
