### ISSUE TITLE
inspections

### ISSUE THREAD

**Issue by fiunchinho** [xxpxxxxp/intellij-plugin-golangci-lint#14]
How do I configure it so that golangci-lint errors show up as inspection warnings in the editor?

I have this configured

![image](https://user-images.githubusercontent.com/627038/78771647-ceccc800-7990-11ea-90f9-bade2a8ae054.png)

and this

![image](https://user-images.githubusercontent.com/627038/78771499-88776900-7990-11ea-8c8d-c83269f3fa23.png)

But the warnings that I get when running golangci-lint locally don't show up as inspection warnings.

**Comment by xxpxxxxp** [comment]
@fiunchinho From your config it's all good for the plugin to work. The second config is not necessary.
If you don't have any golangci-lint inspection show in editor, it might run into issues. Would you please find and paste me any error log? You can find the log by click 'Help' - 'Show Log in Finder'

**Comment by fiunchinho** [comment]
It looks like it's not capable of loading dependencies?
```
WARN -                      go-linter - Run error: level=warning msg="[runner] Can't run linter goanalysis_metalinter: SA1006: failed prerequisites: [inspect@_/home/jose/dev/src/github.com/giantswarm/azure-collector/service/collector: analysis skipped: errors in package: [/home/jose/dev/src/github.com/giantswarm/azure-collector/service/collector/deployment.go:6:2: could not import github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources (deployment.go:6:2: cannot find package \"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources\" in any of:\n\t/usr/lib/go-1.14/src/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources (from $GOROOT)\n\t/home/jose/go/src/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources (from $GOPATH)) 
```

I'm using `dep`. When running golangci-lint as file watcher everything works just fine.

**Comment by fiunchinho** [comment]
Can environment variables be set? for `GOROOT=$GOROOT$;GOPATH=$GOPATH$;PATH=$GoBinDirs$`

**Comment by xxpxxxxp** [comment]
@fiunchinho The plugin is reading Go plugin's GOPATH settings. Normally it works, because if the Go plugin cannot find the right package, it will show red in editor (symbol cannot be resolved)

For your situation, do you have 2 Go installed? That saying, does your shell use different GOROOT as the IDE?

Please try add a **Project GOPATH** that those package located in:
![image](https://user-images.githubusercontent.com/1585918/78778240-8bdd1580-79cd-11ea-8b68-f6e73803efaa.png)

**Comment by fiunchinho** [comment]
Testing a different project that uses go modules, it works fine. So it only fails when using `dep` and having dependencies on the `vendor` folder.

The GOPATH and GOROOT are configured properly at the project level. I don't have several go installations AFAIK.

Any ideas?

**Comment by xxpxxxxp** [comment]
It might be a problem with dep integration. I'll check later and fix it if possible. Thanks for your help @fiunchinho .

**Comment by fiunchinho** [comment]
It's strange. Intellij can find my dependencies in the vendor folder. I can build and run my project just fine.
It's like this plugin it's trying to use a different GOPATH or go configuration?

Thanks for taking a look.

**Comment by xxpxxxxp** [comment]
@fiunchinho I tested the plugin with https://github.com/golang/dep and it works...
Essentially the plugin is running golangci-lint in background with some parameters. I'll add a debug feature to print out the exact parameters, then we could run it manually and see what's wrong.

**Comment by fiunchinho** [comment]
Keep me posted. Thanks.

**Comment by fiunchinho** [comment]
if it helps
```
Can't run linter goanalysis_metalinter: inspect: analysis skipped: errors in package: [/home/jose/dev/src/github.com/giantswarm/azure-collector/service/collector/deployment.go:6:2: could not import github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources
deployment.go:6:2: cannot find package \"github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources\" in any of:
	/usr/lib/go-1.14/src/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources (from $GOROOT)
	/home/jose/go/src/github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-05-01/resources (from $GOPATH)
```

This is my `$GOPATH`

![image](https://user-images.githubusercontent.com/627038/78810590-d27c4100-79c8-11ea-8b7f-cb039543d53b.png)

`$GOROOT` matches the one in the error message

![image](https://user-images.githubusercontent.com/627038/78810617-ddcf6c80-79c8-11ea-819a-cd594616e7c4.png)

my dep configuration

![image](https://user-images.githubusercontent.com/627038/78810677-f2ac0000-79c8-11ea-8be3-022697f73bea.png)

**Comment by xxpxxxxp** [comment]
Thanks @fiunchinho ! Kind of get the problem, did you manually added the global GOPATH? Could you add the same path to Project GOPATH and see if the plugin works?

**Comment by fiunchinho** [comment]
I don't recall adding the global GOPATH. Adding the project GOPATH works!

**Comment by xxpxxxxp** [comment]
Thanks @fiunchinho , that should be the problem. The plugin didn't take manually added Global GOPATH now. I'll fix that in next release.
