### ISSUE TITLE
Failed to discover go env: failed to run 'go env': exit status 2

### ISSUE THREAD

**Issue by SouthWind6510** [xxpxxxxp/intellij-plugin-golangci-lint#146]
I saw this error in idea.log:
`level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 2: stderr: go: cannot find GOROOT directory: /Users/xxx/.asdf/shims/go\n"
. Please make sure the project has no syntax error.`
but `GOROOT` in Goland setting is this:
![image](https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/assets/62692752/f1821b88-8f11-461a-9b7e-7d0e646b32c2)

**Comment by xxpxxxxp** [comment]
Hi @SouthWind6510 , would you try restart IDE and see if the problem persists, the plugin maybe using an old config.
