### ISSUE TITLE
Env var to configure 'Path to golangci-lint'

### ISSUE THREAD

**Issue by f-blass** [xxpxxxxp/intellij-plugin-golangci-lint#153]
I have installed golangci-lint via homebrew to `/opt/homebrew/bin/golangci-lint` which is a symlink to the current version e.g. `../Cellar/golangci-lint/1.55.2/bin/golangci-lint`.
Whenever I upgrade golangci-lint the plugin will remove the configuration, even though I use the symlink and I have to re-configure it.

Is it possible to read the path to the executable from a env variable so I do not have to reconfigure it after every upgrade?

**Comment by xxpxxxxp** [comment]
Hi @f-blass , the plugin should not follow symlink anymore. Please reselect the executable in the setting to `/opt/homebrew/bin/golangci-lint`, use the open button. If in the dropdown it shows `../Cellar/golangci-lint/1.55.2/bin/golangci-lint` please let me know.

**Comment by f-blass** [comment]
Hi @xxpxxxxp thanks! It still shows the symlink, so probably it actually is already fixed. Thanks for your answer!
