### ISSUE TITLE
How and where can i see the results of plugin work?

### ISSUE THREAD

**Issue by RomanKosyii** [xxpxxxxp/intellij-plugin-golangci-lint#19]
I've installed plugin on Goland 2020.1, but i don't get where can i view the results.
I write the code - can't see nothing :)

Could you please help? Thanks for work!

**Comment by xxpxxxxp** [comment]
@RomanKosyii 
The first time after you installed the plugin, you should see a popup like
![image](https://user-images.githubusercontent.com/1585918/79688528-74314700-8281-11ea-913a-3e8de06c73e1.png)

You can click 'Configure' to open the setting dialog, or go to 'Preferences' - 'Tools' - 'Go Linter' 
![image](https://user-images.githubusercontent.com/1585918/79688571-ad69b700-8281-11ea-87d7-d38d963fb275.png)

Then if you already have golangci-lint executable on disk, you can choose it in the combobox or 'Open...' it. If you don't have it yet you can simply click 'Get Latest', the plugin will download it for you. After that you should see this:
![image](https://user-images.githubusercontent.com/1585918/79688622-fe79ab00-8281-11ea-86f3-7d1492401620.png)

Enable linters you want. If you want to use config file, click 'Document...' will take you to official site to learn how to do that.

After all that done, you should be able to see inspections in your editor, like:
![image](https://user-images.githubusercontent.com/1585918/79688724-c1fa7f00-8282-11ea-9e8f-add9581e4f34.png)

If there's error popup in the right-bottom corner please let me known.

**Comment by RomanKosyii** [comment]
Strange. I've done all these operations, added same code with defer
![image](https://user-images.githubusercontent.com/43781324/79697656-66cd8a00-828c-11ea-8f7b-2b882d3c7a9e.png)

and still no inspections on this one.
I'm using Windows. I've downloaded the latest with the button.
Inspection level is 
![image](https://user-images.githubusercontent.com/43781324/79697668-7c42b400-828c-11ea-9910-b9bfc9a5f8a5.png)

And the settings are pretty the same
![image](https://user-images.githubusercontent.com/43781324/79697674-9381a180-828c-11ea-8089-917765c07016.png)

![image](https://user-images.githubusercontent.com/43781324/79697679-9e3c3680-828c-11ea-8ffe-07b8dbdb2ec3.png)

**Comment by xxpxxxxp** [comment]
@RomanKosyii 
Please make sure your project could successfully build. The linter only works if the project could build.
If the plugin still doesn't work, please paste related log in idea log here. You can find idea log by 'Help' - 'Show Log in Explorer', then search for "go-linter"

**Comment by Metalscreame** [comment]
Thanks! That's the case. The project I tested could not be compiled. Opened normal project - everything worked fine. Thanks!

**Comment by xxpxxxxp** [comment]
@Metalscreame Thanks for confirming, I guess this is another account of yourself. Issue closed.
