### ISSUE TITLE
Running error: --enable-all and --disable-all options must not be combined

### ISSUE THREAD

**Issue by mac89** [xxpxxxxp/intellij-plugin-golangci-lint#21]
I'm running it using default settings and golangci-lint@1.26.0 and get the following error:

`2020-05-15 08:53:12,230 [  98761]   WARN -                      go-linter - Run error: level=error msg="Running error: --enable-all and --disable-all options must not be combined"
. Usually it's caused by wrongly configured parameters or corrupted with config file. `

Version:
`golangci-lint has version 1.26.0 built from 6bd10d0 on 2020-05-01T15:31:27Z
`

**Comment by xxpxxxxp** [comment]
@mac89 Do you have a `.golangci.yml`(or .golangci.toml/.golangci.json) config file anywhere in your project folder?

**Comment by mac89** [comment]
No, none of those.

**Comment by xxpxxxxp** [comment]
OK, then have you set a custom option like `--enable-all` in `Go Linter` setting in IDEA?

**Comment by mac89** [comment]
I've just found the issue. I had a custom config file set in the options and the checkbox was disabled.
I just changed it to something random:
![Annotation 2020-05-15 094253](https://user-images.githubusercontent.com/2988607/82024718-7e800e80-9690-11ea-8f55-520774286e94.png)

And get this accompanying error:
`2020-05-15 09:40:57,812 [  81218]   WARN -                      go-linter - Run error: level=error msg="Can't get config for command line: can't parse args: unknown flag: --what"
. Usually it's caused by wrongly configured parameters or corrupted with config file. `

Seems like the checkbox setting is ignored.

**Comment by xxpxxxxp** [comment]
Yeah that's a bug, I'll fix it in next release. Seems nobody is seriously using that before...
Besides that, have the plugin works now?

**Comment by mac89** [comment]
Yeah, all good.

**Comment by xxpxxxxp** [comment]
Thanks for confirming.

**Comment by xxpxxxxp** [comment]
Fixed in last commit.
