### ISSUE TITLE
Failed to get latest release [Windows/1.14.2]

### ISSUE THREAD

**Issue by hugmouse** [xxpxxxxp/intellij-plugin-golangci-lint#22]
Can't download the linter 🤔 

Go version: `go1.14.2 windows/amd64`
Goland version: `2020.1.2 (#GO-201.7223.97)`

Error: `Collection contains no element matching the predicate`

![goland64_oBaJH7gcr1](https://user-images.githubusercontent.com/44648612/82220019-af8e6680-9950-11ea-9503-6cac5390bebe.png)

**Comment by xxpxxxxp** [comment]
Thanks @hugmouse 
Starting from v1.27.0 golangci-lint changed their windows release name. You can see that from https://github.com/golangci/golangci-lint/releases. 
While this is an easy fix for me, I'm not sure if they have made this decision permanent. Seems to me it's introduced unintentionally in https://github.com/golangci/golangci-lint/commit/77e211ba75b7802fe5e40b276bca0e928553fc7f#diff-3a895417c300af3c34fab6ebb556e984
I'll hold the change until next golangci-lint release. Please download latest release manually, sorry for trouble.

**Comment by xxpxxxxp** [comment]
Turns out golangci-lint is impacted by their upstream https://github.com/goreleaser/goreleaser/issues/1500
The problem is addressed at
https://github.com/golangci/golangci-lint/issues/1157
`Get Latest` should be working now, without change. Thanks for reporting.

**Comment by dakyskye** [comment]
Well that's on Linux ![image](https://user-images.githubusercontent.com/32128756/106708471-5c5a6200-660c-11eb-82bd-40d6b9091306.png)

**Comment by xxpxxxxp** [comment]
Hi @dakyskye , just as the message said, the plugin failed to download the latest `golangci-lint` executable to `/usr/local/bin/`, because of restricted permission. Please manually download & unzip it from `https://github.com/golangci/golangci-lint/releases` (or through apt / yum / pacman of your system), then select the executable path in plugin settings.

**Comment by dakyskye** [comment]
Yeah, I did that, thanks though. I was just complaining that it can not auto download, because it has chosen wrong directory, where it is not meant to have permissions, so it could possibly be changed.

**Comment by xxpxxxxp** [comment]
Any suggestion for dest folder?

**Comment by dakyskye** [comment]
Probably `~/.local/share/bin`, but the plugin could ask the user to actually select what directory they want.
