### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by karel-3d** [xxpxxxxp/intellij-plugin-golangci-lint#23]
The current implementation blocks the IDE when the linter is running.

If the linting takes longer, it gets very annoying.

Can the lint process be run in background, as is (for example) goland current indexing?

**Comment by karel-3d** [comment]
Hm, this seems to evaporate with `--concurrency 4` custom option. I think that's just because it's 4 times faster and I no longer notice the delays. :)

**Comment by xxpxxxxp** [comment]
Thanks @karel-3d 
I'm working on this, actually it's not easy so I cannot promise an ETA.
IDEA is block waiting on an inspector to return issues, so we have to choose return nothing immediately / return something but block UI. I'm trying some hack to workaround.
Let's keep this ticket to track progress.

**Comment by karel-3d** [comment]
I feel like in the case of WebStorm, the ESLint is not blocking the main thread. But I might be wrong and ESLint is just faster.

**Comment by xxpxxxxp** [comment]
Thanks! I'm reading ESLint plugin source code to see if any inspiration.

**Comment by karel-3d** [comment]
I'm sorry, I might be wrong and it was TSLint

https://github.com/JetBrains/intellij-plugins/tree/master/tslint

**Comment by xxpxxxxp** [comment]
@karel-3d I've managed to improve the performance a bit, would you please provide any feedback?

**Comment by karel-3d** [comment]
SO much better!!! Should I close this issue now?

**Comment by xxpxxxxp** [comment]
Thanks for confirming. I'll close this then.
