### ISSUE TITLE
the plugin is "asking" to be enable in all projects

### ISSUE THREAD

**Issue by danysz** [xxpxxxxp/intellij-plugin-golangci-lint#24]
The "plugin" is asking to enable it in all projects including also in the projects which are not "go".
It's really bothering.

**Comment by xxpxxxxp** [comment]
Thanks! I'll work on a solution to detect no Go projects. And FYI the plugin will not have any overhead even enabled for no Go projects.

**Comment by xxpxxxxp** [comment]
I've added an option to disable the check once for all, please check if that helps.

**Comment by xxpxxxxp** [comment]
@danysz haven't heard from you recently, I'm closing this issue, feel free to reopen it if necessary.
