### ISSUE TITLE
Question: When golangci-lint execute?

### ISSUE THREAD

**Issue by sonatard** [xxpxxxxp/intellij-plugin-golangci-lint#25]
I fix warning by golangci-lint and save file but warning is not deleted on IntelliJ IDEA.

**Comment by xxpxxxxp** [comment]
Generally, golangci-lint is running when
* You open a go file the first time
* You save a go file

It's not running when you are editing a go file / it's not a go file.

As the execution will take a few sec, the warning will be removed after you fix it and saved the file in a few sec.
Also, Goland may decide to delay the next execution if there's one running (eg: for another go file), so overall the warning should be removed in 1min. If that's not the case, please fill a bug for me.

**Comment by sonatard** [comment]
Thanks!! I create https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/issues/26
