### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by fighterlyt** [xxpxxxxp/intellij-plugin-golangci-lint#27]
OS:  macOS Catalina 10.15.5 (19F101)
IDE : goland 2020.1.3
BUG:
    I use golangci-lint command line tool for months. I have a custom config file which enabled **wsl**check . So I wrote  some code that violate wsl rule , and nothing happens?

**Comment by xxpxxxxp** [comment]
@fighterlyt 兄弟把设置截图给我看一下
![image](https://user-images.githubusercontent.com/1585918/85584446-bc018f80-b671-11ea-9c51-382668befbaa.png)

**Comment by fighterlyt** [comment]
![截屏2020-06-25 上午10 15 39](https://user-images.githubusercontent.com/1442870/85645636-e6346b00-b6cc-11ea-91a8-18e6d07df6c3.png)
配置来了

**Comment by xxpxxxxp** [comment]
看起来配置没问题，配置文件发现了而且wsl也是开启的。确定project本身是可以go build过的？

**Comment by fighterlyt** [comment]
我是 go run main.go

**Comment by xxpxxxxp** [comment]
除了wsl其他linter有能用的吗？
你的code如果是open source的话，在github上能给我看一下吗？

**Comment by fighterlyt** [comment]
不好意思，不是open source, 刚发现linter可以用，但是没有auto fix

**Comment by xxpxxxxp** [comment]
OK，可以用就好。auto fix不是所有linter都有的，wsl这个linter就没有，因为规则略复杂我都没搞清楚...
