### ISSUE TITLE
The linter plug-in configuration does not take effect

### ISSUE THREAD

**Issue by CrazyTomatoOo** [xxpxxxxp/intellij-plugin-golangci-lint#30]
Even if I disable all the plug-ins, it can still scan for errors. I enable all plug-ins, WSL and other plug-ins do not work. Is it a bug or a wrong way to use it？

**Comment by xxpxxxxp** [comment]
Hi @CrazyTomatoOo , for your questions
1. Will fix soon
2. I need more information, is there a flashing error on right down corner of IDE in such case?
Could you paste output of `golangci-lint run --enable-all --out-format json ./...` running under project root?

**Comment by xxpxxxxp** [comment]
@CrazyTomatoOo Please help to check if the new release resolved this issue, thanks.

**Comment by CrazyTomatoOo** [comment]
Sure, I'd like to.



---Original---

**Comment by CrazyTomatoOo** [comment]
It seems to have been fixed. Thanks a lot.

**Comment by xxpxxxxp** [comment]
Thanks for confirming.\
