### ISSUE TITLE
Freeze IDE while codding.

### ISSUE THREAD

**Issue by EugeneAndrosovPaser** [xxpxxxxp/intellij-plugin-golangci-lint#33]
Hello, I have a problem with freezing IDE while codding.

I see that while I'm writing a function time to time launching golangci-ling linter for generating issues, but I do not completely write code. In this case, I see freezing IDE. Also, in this case, I see an error about Linter has the wrong configuration.

Can you add an option to launch linter when I do Save action like in "File watcher"?

Linter launches from 1 to 5 times in a minute and it degrades IDE performance.

**Comment by xxpxxxxp** [comment]
Hi @EugeneAndrosovPaser , which version of the plugin are you using? You can see that from plugin page.

**Comment by xxpxxxxp** [comment]
Track with #38
