### ISSUE TITLE
Wrong permission on downloaded golangci-lint

### ISSUE THREAD

**Issue by fgblomqvist** [xxpxxxxp/intellij-plugin-golangci-lint#34]
I used the "Get Latest" feature to download the latest golangci-lint. However, it didn't set the executable permission on the file so it doesn't work until you manually do. Tbh, I think you should just force people to install it on their own. I think's that's a better practice.

**Comment by xxpxxxxp** [comment]
It should set the right permission, which platform does the issue happen, win/linux/mac?

**Comment by fgblomqvist** [comment]
It happened on mac, have not tried elseswhere.

**Comment by xxpxxxxp** [comment]
I've tried and it works well on my mac, let's keep it here to see if anyone has the same issue.

**Comment by prigornitskiy** [comment]
Same issue

lrwxr-xr-x   1 ionix  admin    29B  1 окт 18:53 gofmt -> ../Cellar/go/1.15.2/bin/gofmt
-rw-r--r--   1 ionix  admin    21M  8 окт 12:08 golangci-lint

**Comment by xxpxxxxp** [comment]
Fixed the issue and will release soon, thanks @fgblomqvist @prigornitskiy !
