### ISSUE TITLE
Incorrect command to run the linter

### ISSUE THREAD

**Issue by fgblomqvist** [xxpxxxxp/intellij-plugin-golangci-lint#35]
This is what's getting run according to the IntelliJ logs:
```
cd /path/to/the/current/dir && export PATH=/Users/fblomqvist/.gvm/gos/go1.13.15/bin:/usr/bin:/bin:/usr/sbin:/sbin && export GOPATH= && /usr/local/bin/golangci-lint run --out-format json --concurrency 2 --max-issues-per-linter 0 --max-same-issues 0 --maligned.suggest-new . 
```

This is very incorrect.
This is all you should run:
```
/usr/local/bin/golangci-lint run --out-format json --concurrency 2 --max-issues-per-linter 0 --max-same-issues 0 --maligned.suggest-new /path/to/the/current/dir
```

You shouldn't mess with PATH or GOPATH, it causes weird errors for me and probably for a lot of other people. Currently the linter is unable to run.

**Comment by fgblomqvist** [comment]
Perhaps you need to change the workdir, but you shouldn't have to change the PATH and GOPATH.

**Comment by xxpxxxxp** [comment]
Hi @fgblomqvist , the command above is for debug in case of the plugin failed, it's not what actually get runned inside the plugin.
The reason to change GOPATH is that people might set different GOPATH inside Goland's setting, diff with system-wide settings. You can check that at Goland settings.
Change PATH is same: people might have Go SDK set in Goland, while not set Go binary in system PATH.
Please try run the command and see if it's failled for any problem.

**Comment by xxpxxxxp** [comment]
For example:
system GOPATH is added if checked `use GOPATH that's defined in system environment`
custom GOPATH might be added in `Project GOPATH` above
![image](https://user-images.githubusercontent.com/1585918/93084104-24d33380-f6c6-11ea-8140-f64729b9f554.png)
