### ISSUE TITLE
[2019.3.3] Doesn't work with golangci-lint executable by symlink

### ISSUE THREAD

**Issue by paskal** [xxpxxxxp/intellij-plugin-golangci-lint#4]
[This code](https://github.com/paskal/go-prisma/tree/d5c2c52e363ef2b4febb0db8a4026824604fbdf4) at commit `d5c2c52e363ef2b4febb0db8a4026824604fbdf4` shows a [couple of problems](https://github.com/paskal/go-prisma/runs/444622559#step:6:6) by golangci-lint:

```
➜  go-prisma git:(master)   golangci-lint run ./...
prisma.go:63:27: Error return value of `response.Body.Close` is not checked (errcheck)
        defer response.Body.Close()
                                 ^
prisma.go:15:1: ST1000: at least one file in a package should have a package comment (stylecheck)
package prisma
^
```

However, after I've installed Go Linter on Intellij Idea, nothing changed for me and I don't see these problems shown as inspections result.

Version info:
```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Runtime version: 11.0.3+12-b347 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: ParNew, ConcurrentMarkSweep
Memory: 990M
Cores: 4
Registry: 
Non-Bundled Plugins: com.intellij.plugins.watcher, Pythonid, awesome.console, com.dubreuia, com.github.mfedko.idea.plugins.filelanguage, com.jetbrains.plugins.ini4idea, com.tabnine.TabNine, org.jetbrains.plugins.go-template, org.jetbrains.plugins.go, com.ypwang.plugin.go-linter, ideanginx9, mobi.hsz.idea.gitignore, org.sylfra.idea.plugins.linessorter
```

**Comment by paskal** [comment]
When I've opened the path to binary in file browser (by clicking `Open` button on plugin settings page), which is default `/usr/local/bin/golangci-lint`, it added new entry with path to binary by simlink and then started working:
<img width="580" alt="image" src="https://user-images.githubusercontent.com/712534/74480240-d734e500-4eb0-11ea-8d7e-5b940f0b4275.png">

I wonder if it's possible to have it working with the symlink?
```
➜  go-prisma git:(master) ls -l /usr/local/bin/golangci-lint
lrwxr-xr-x  1 user  admin  48 Feb 10 22:09 /usr/local/bin/golangci-lint -> ../Cellar/golangci-lint/1.23.6/bin/golangci-lint
```

Otherwise, I'll need to change the path to executable with each update, as my golangci-lint is installed with homebrew.

**Comment by xxpxxxxp** [comment]
Thanks paskal, I'll fix this ASAP.

**Comment by rumstead** [comment]
I also have this problem. Is there a way to track the plugin version to commits?
