### ISSUE TITLE
Plugin asks to configure project that I already configured

### ISSUE THREAD

**Issue by yngvark** [xxpxxxxp/intellij-plugin-golangci-lint#40]
Every time I open a project I get this

![image](https://user-images.githubusercontent.com/562343/98245738-a9795a00-1f71-11eb-9cd0-e9089e92af4a.png)

`golanci-lint executable is need for linter inspection work....`

However, I have configured this thing several times, but it seems to be forgotton as soon as I close the project. The linter is working, so I know the configuration works.

**Comment by xxpxxxxp** [comment]
Can I have your OS version `uname -a`
And path to the executable:
![image](https://user-images.githubusercontent.com/1585918/98249284-09dbbc00-1fb1-11eb-92f0-c3dd765f954f.png)
And most importantly, the permission of the executable
![image](https://user-images.githubusercontent.com/1585918/98249520-4a3b3a00-1fb1-11eb-9dec-6ebff89f15e4.png)

**Comment by yngvark** [comment]
Sure:

```
$ uname -a
Linux yngvarxd 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Path: `/home/yngvar/go/bin/golangci-lint`
![image](https://user-images.githubusercontent.com/562343/98345764-62dd3b80-2015-11eb-8a44-2f6ee189d368.png)


```
$ ll /home/yngvar/go/bin/golangci-lint
-rwxrwxr-x 1 yngvar yngvar 31457168 sep.  28 15:35 /home/yngvar/go/bin/golangci-lint*

```

**Comment by xxpxxxxp** [comment]
Hi @yngvark , so far I cannot repro the bug, I need your help, might be a little complicated:
Please help to check if
`~/.config/JetBrains/GoLand2020.2/options/other.xml`
(change IDE name and version accordingly)
contains a field naming `golangci-lint`
![image](https://user-images.githubusercontent.com/1585918/98360658-2b967b00-2065-11eb-824a-607c33c64b97.png)

Then please reopen the project, configure the executable, check again.
I'm suspecting GoLand has a permission issue, it may not save config correctly.

**Comment by yngvark** [comment]
For me the file is in `~/.config/JetBrains/IntelliJIdea2020.2/options/other.xml`. Here I have 

```
<property name="golangci-lint" value="$USER_HOME$/go/bin/golangci-lint" />
```

I did the following:
* Opened my project
* The popup appeared again. Now I changed the golangci-lint executable to something else (just a random executable in the same folder).

The `~/.config/JetBrains/IntelliJIdea2020.2/options/other.xml` immediately was updated with the new executable.

* I closed the project, then opened it again. I verified the other.xml was still the same.
* Then I updated the executable golangci-lint back to its original: `$USER_HOME$/go/bin/golangci-lint`
* I verified that other.xml was correctly updated with the new value.
* I closed the project, and opened it again. I still have the same popup.

Notice I'm using IntelliJ with Go, not GoLand.

**Comment by xxpxxxxp** [comment]
Thank you, are you using a custom build of golangci-lint? What's the output of
`/home/yngvar/go/bin/golangci-lint version`

The plugin is trying to verify the output like
`golangci-lint has version 1.32.2 built from 52d26a3 on 2020-11-03T01:15:38Z`
If it cannot match the pattern, it thinks the `golangci-lint` is not valid.

**Comment by yngvark** [comment]
```
$ /home/yngvar/go/bin/golangci-lint version
golangci-lint has version v1.31.0 built from (unknown, mod sum: "h1:+m9I3LEmxXLpymkXRPkDQGzOVBmBYm16UtDiXqZxWek=") on (unknown)
```

I can't remember how I installed golangci-lint anymore. But I guess you are right, I must have made a custom build somehow :persevere:

I downloaded latest release, now it shows

```
$ /home/yngvar/go/bin/golangci-lint version
golangci-lint has version 1.32.2 built from 52d26a3 on 2020-11-03T01:15:38Z
```

And amazingly, the popup is now gone! Sorry for your trouble, but thanks so much for your help.

**Comment by xxpxxxxp** [comment]
Thanks for confirming, I will update the check accordingly, custom build should also be considered valid.
