### ISSUE TITLE
Go linter stopped working

### ISSUE THREAD

**Issue by iangregsondev** [xxpxxxxp/intellij-plugin-golangci-lint#42]
Hi,

I am using the latest go linter plugin, latest go linter executable from brew, latest intellij

and BigSur :-)

The IDE doesn't seem to shout at me anymore, i have purposely put some errors in the file, like blocks being next to declarations etc but nothing..

Is there a way to see whats happening..

I will leave a screenshot here that might explain it 

![image](https://user-images.githubusercontent.com/2370364/99180828-ef7cad80-2729-11eb-85aa-dc9c8c63b0a8.png)

I have enabled ALL linters.

**Comment by xxpxxxxp** [comment]
WOW BigSur! Haven't updated my mac. Please check IDEA log to see anything abnormal, should be in `Help` - `Show log in Finder`.

**Comment by iangregsondev** [comment]
Nice!, this was weird :-)

So I found the log file and noticed it was massive :-(

So I closed intellij

removed all the files from the log directory - there were dumps as well... restarted intellij and it works :-)

Thanks - closing!

**Comment by iangregsondev** [comment]
@xxpxxxxp The version published in Brew (mac) for 1.42.1 still does not work...

❯ golangci-lint --version

golangci-lint has version 1.42.1 built from 54f4301 on 2021-09-04T14:39:09Z

--

Checked inside the idea.log and I don't see anything strange..

Are you sure the correct version has been pushed to Brew ?

**Comment by xxpxxxxp** [comment]
Hi @iangregsondev , I'm also using `golangci-lint` v1.42.1 installed from HomeBrew, works for me. Please provide a toy project that doesn't work for you to help me debug the issue, thanks.

**Comment by iangregsondev** [comment]
Yep- my bad. It started working.. uninstalled and reinstalled via brew and cleared the goland cache.

closing - thanks
