### ISSUE TITLE
No linters shown in IDEA 2020.3

### ISSUE THREAD

**Issue by steebchen** [xxpxxxxp/intellij-plugin-golangci-lint#45]
I am on macOS Big Sur 11.1 and 2020.3 IU-203.5981.155, and the binary exists and works but no linters are shown. It worked before; I'm not sure if updating Big Sur or IJ or something else is the issue:

<img width="984" alt="image" src="https://user-images.githubusercontent.com/5013932/103229079-ea379300-4964-11eb-9a4f-0e1b75b3b4c8.png">

Any tips on what I could try or provide to help solve this?

Looks like there was just a new release of golangci-lint@v1.34.0, but whatever version I had before (1.31? I think) had the same problem.

It worked well until a few days ago, so I guess some change around OS/IJ/golangci-lint might cause this.

**Comment by mehmet-ozgul** [comment]
I have the same issue. It looks like [gci](https://github.com/daixiang0/gci) is broken and its exception terminates the go-linter's discovery loop:
```
java.lang.Throwable: Cannot get linters from running result: RunProcessResult(returnCode=2, stdout=, stderr=panic: err: go command required, not found: exec: "go": executable file not found in $PATH: stderr: 

goroutine 1 [running]:
github.com/daixiang0/gci/pkg/gci.init.0()
	/home/runner/go/pkg/mod/github.com/daixiang0/gci@v0.2.7/pkg/gci/gci.go:41 +0x106
)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.ypwang.plugin.GolangCiOutputParser.parseLinters(GolangCiOutputParser.kt:68)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$initializeLinters$14(GoLinterSettings.java:263)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by xxpxxxxp** [comment]
Hi @steebchen @mehmet-ozgul 
I see golangci-lint has released 3 versions last day (v1.33.1 v1.33.2 v1.34.0), all breaks this plugin. Not sure whether they are having any regression.

Now the latest working version is v1.33.0, please use that if necessary
https://github.com/golangci/golangci-lint/releases/tag/v1.33.0

I'll keep an eye on their releases and see what I can do on the plugin side.

**Comment by steebchen** [comment]
Indeed; I'll just stay on v1.33.0 for now then.

**Comment by koalacxr** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/6064099/103391762-fafb2b00-4b55-11eb-9508-db563ff9bbcd.png)

And then select project root:
![image](https://user-images.githubusercontent.com/6064099/103391849-4c0b1f00-4b56-11eb-96d3-f3d63f55759d.png)
![image](https://user-images.githubusercontent.com/6064099/103391877-647b3980-4b56-11eb-9414-83827f317d31.png)

**Comment by xxpxxxxp** [comment]
Hi @koalacxr , have you set 'GOROOT' in IDE? The plugin needs to know 'GOROOT' to work correctly.
![image](https://user-images.githubusercontent.com/1585918/103394226-2126c800-4b62-11eb-9786-7bf68a6c08d8.png)

**Comment by koalacxr** [comment]
> have you set 'GOROOT' in IDE? The plugin needs to know 'GOROOT' to work correctly.

The Go version upgraded from 1.15.5 to 1.15.6 still has the same problems.
![image](https://user-images.githubusercontent.com/6064099/103409609-8ef2e400-4ba2-11eb-9641-24e100a1179c.png)

![image](https://user-images.githubusercontent.com/6064099/103409621-9c0fd300-4ba2-11eb-9742-dcee6ac9b1d8.png)

**Comment by xxpxxxxp** [comment]
Hi @koalacxr , I see 'GOROOT' is set, please make sure it's saved, then the 'Go Linter' page still not working?

**Comment by koalacxr** [comment]
> Hi @koalacxr , I see 'GOROOT' is set, please make sure it's saved, then the 'Go Linter' page still not working?

Be sure to save the Settings 'GOROOT' and close the IDE, then open the IDE again, same problem.

**Comment by xxpxxxxp** [comment]
@koalacxr I think I known the reason now, will fix it soon.

**Comment by mehmet-ozgul** [comment]
Good news. GoLinter 1.4.8 (It is just updated) works with golangci-lint 1.34.1 on MacOS 11.1.

**Comment by xxpxxxxp** [comment]
Great! @koalacxr does it work now?

**Comment by koalacxr** [comment]
> Great! @koalacxr does it work now?

The problem remains.

$golangci-lint --version
golangci-lint has version 1.34.1 built from d7dd233 on 2020-12-29T06:20:54Z

**Comment by xxpxxxxp** [comment]
@koalacxr my fault, I forgot to mention, I've recalled v1.4.8 from jetbrains market, then published that version again, to fix case above. You have to uninstall the plugin, then install it from market again, sorry for troubles.

**Comment by steebchen** [comment]
I can confirm it works in the latest version. Thanks!

@koalacxr Please create a new issue since your error problem is not the same as the one I initially described. Thanks.
