### ISSUE TITLE
No linters shown in IDEA 2020.3.1

### ISSUE THREAD

**Issue by koalacxr** [xxpxxxxp/intellij-plugin-golangci-lint#46]
I have the problem.

![](https://user-images.githubusercontent.com/6064099/103391762-fafb2b00-4b55-11eb-9508-db563ff9bbcd.png)

![](https://user-images.githubusercontent.com/6064099/103391849-4c0b1f00-4b56-11eb-96d3-f3d63f55759d.png)

![](https://user-images.githubusercontent.com/6064099/103391877-647b3980-4b56-11eb-9414-83827f317d31.png)

![](https://user-images.githubusercontent.com/6064099/103409609-8ef2e400-4ba2-11eb-9641-24e100a1179c.png)

![](https://user-images.githubusercontent.com/6064099/103409685-d6797000-4ba2-11eb-8689-dfb1d54c3673.png)

**Comment by koalacxr** [comment]
This prompt box pops up every time you open the project.
![image](https://user-images.githubusercontent.com/6064099/103449087-26a91d00-4cde-11eb-8f9b-4dd2c7477ba2.png)

**Comment by koalacxr** [comment]
java.lang.Exception: Failed to Discover Linters: RunProcessResult(returnCode=2, stdout=, stderr=panic: go [-e -json -compiled=true -test=false -export=false -deps=false -find=true -- std]: exit status 1: go: github.com/aliyun/aliyun-oss-go-sdk@v2.1.5+incompatible: Get "https://proxy.golang.org/github.com/aliyun/aliyun-oss-go-sdk/@v/v2.1.5+incompatible.mod": dial tcp 172.217.160.81:443: i/o timeout


goroutine 1 [running]:
github.com/daixiang0/gci/pkg/gci.init.0()
	/home/runner/go/pkg/mod/github.com/daixiang0/gci@v0.2.7/pkg/gci/gci.go:41 +0x106
)
	at com.ypwang.plugin.GolangCiOutputParser.parseLinters(GolangCiOutputParser.kt:33)
	at com.ypwang.plugin.form.GoLinterSettings.lambda$initializeLinters$15(GoLinterSettings.java:264)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by xxpxxxxp** [comment]
哈哈兄弟看起来是国人，抱歉我上个issue忘了跟你说，v1.4.8这个版本在你跟我说还有问题之后我就召回了，然后改了一些代码重新发布了一次。你需要从IDE里卸载这个插件，再重新安装一次（应该不需要重启IDE，但保险起见最好重启一下），这样就会是最新的版本，应该会修好你这个问题。

你的情况跟别人不一样的是你的 go 是放在 /user/local 下的，之前的插件默认认为这个路径在 PATH 里，然而实际上又不是，就崩了。

**Comment by koalacxr** [comment]
谢谢兄弟，辛苦了。
按照你的方案：卸载插件，重启了IDE，再安装重新安装插件，重启IDE，还是有如下问题：

![](https://user-images.githubusercontent.com/6064099/103449087-26a91d00-4cde-11eb-8f9b-4dd2c7477ba2.png)


选择project root项目根目录，如下异常：
![](https://user-images.githubusercontent.com/6064099/103391849-4c0b1f00-4b56-11eb-96d3-f3d63f55759d.png)

**Comment by xxpxxxxp** [comment]
emmm这个还是召回之前的版本，新的版本里我改了提示信息的文字，怕是Goland有某种plugin的cache
我来说一个稍微麻烦的终极方案吧

* 卸载这个plugin
* 重启IDE
* 从官方repo里下载最新的版本v1.4.8 https://plugins.jetbrains.com/plugin/12496-go-linter/versions
* 下载完成是一个zip文件
* 在Goland里选择从硬盘安装插件
* 选择刚才的zip文件，确认安装
* 重启IDE

![image](https://user-images.githubusercontent.com/1585918/103451848-0ee48f80-4d04-11eb-9613-646662215357.png)

**Comment by koalacxr** [comment]
> emmm这个还是召回之前的版本，新的版本里我改了提示信息的文字，怕是Goland有某种plugin的cache
> 我来说一个稍微麻烦的终极方案吧
> 
> * 卸载这个plugin
> * 重启IDE
> * 从官方repo里下载最新的版本v1.4.8 https://plugins.jetbrains.com/plugin/12496-go-linter/versions
> * 下载完成是一个zip文件
> * 在Goland里选择从硬盘安装插件
> * 选择刚才的zip文件，确认安装
> * 重启IDE
> 
> ![image](https://user-images.githubusercontent.com/1585918/103451848-0ee48f80-4d04-11eb-9613-646662215357.png)

@xxpxxxxp 按这个方案做了一遍，打开IDE有如下弹框：

![](https://user-images.githubusercontent.com/6064099/103449087-26a91d00-4cde-11eb-8f9b-4dd2c7477ba2.png)

选择项目，如下报错：

![](https://user-images.githubusercontent.com/6064099/103391849-4c0b1f00-4b56-11eb-96d3-f3d63f55759d.png)

**Comment by xxpxxxxp** [comment]
怪不得，我发错版了，没带上最新的commit...
刚刚发了最新的版本，稍等一天就会上线了

**Comment by xxpxxxxp** [comment]
这次我亲自试了一下，保证没有问题了。只需要卸载现有的plugin，再从market安装就好。

**Comment by koalacxr** [comment]
@xxpxxxxp 感谢修复
已经设置了project root，保存都没有问题。再次打开项目，弹出如下图：

![](https://user-images.githubusercontent.com/6064099/103449087-26a91d00-4cde-11eb-8f9b-4dd2c7477ba2.png)

这个比较焦虑，能处理下吗

**Comment by xxpxxxxp** [comment]
设置页面正常了吗？
这个可以先点 `Don't show for this project` ，不影响使用，下个release一起修复吧。

**Comment by koalacxr** [comment]
> Don't show for this project

点了“Don't show for this project”，再次打开还是弹框

**Comment by xxpxxxxp** [comment]
嗯发了一个新版修这个了，还有气他异常吗我一起修了...

**Comment by koalacxr** [comment]
选择projectroot后，有时超时的异常，会弹出goroot选择框，比如项目中含有github.com/ethereum/go-ethereum v1.9.25(去掉这个包就没事)，这个超时最好能修掉。

**Comment by xxpxxxxp** [comment]
这个我去不了的，所有问题的原因是golangci-lint更新了内置linter gci的版本，新版本gci会在init时候尝试load所有的package，这个操作本身可能非常的耗时，取决于import的package大小。我觉得这个操作十分的不合理，做lint的时候也就算了，`golangci-lint version` `golangci-lint linters`时候也这样就不正常，而且gci也不是一个很常用的linter，我准备提issue去了。

**Comment by koalacxr** [comment]
> 这个我去不了的，所有问题的原因是golangci-lint更新了内置linter gci的版本，新版本gci会在init时候尝试load所有的package，这个操作本身可能非常的耗时，取决于import的package大小。我觉得这个操作十分的不合理，做lint的时候也就算了，`golangci-lint version` `golangci-lint linters`时候也这样就不正常，而且gci也不是一个很常用的linter，我准备提issue去了。

@xxpxxxxp 那就修复每次打开项目弹框的问题吧

**Comment by koalacxr** [comment]
升级到1.4.9解决了，感谢

**Comment by xxpxxxxp** [comment]
👍 我试着联系下gci的作者，看样子也是国人，看看能不能把初始化这段优化一下

**Comment by xxpxxxxp** [comment]
golangci-lint最新的release修复了 gci 导致启动慢的问题，可以试一下

**Comment by sunday9th** [comment]
我遇到个类似，但是不一样点的问题
![image](https://user-images.githubusercontent.com/1252279/146288938-025fecfc-32b8-4090-a24a-d380a7c46d2a.png)
![image](https://user-images.githubusercontent.com/1252279/146289062-3088403e-da80-407f-ab0f-7f05aa1618a2.png)
版本是1.5.6
已经做过


> 

这个操作了

**Comment by xxpxxxxp** [comment]
在issue里找不到你这条回复了，是之后删除了吗？

 

From: ***@***.***> on behalf of sunday9th ***@***.***>
Reply-To: xxpxxxxp/intellij-plugin-golangci-lint ***@***.***>
Date: Thursday, December 16, 2021 at 9:07 AM
To: xxpxxxxp/intellij-plugin-golangci-lint ***@***.***>
Cc: xxpxxxxp ***@***.***>, Mention ***@***.***>
Subject: Re: [xxpxxxxp/intellij-plugin-golangci-lint] No linters shown in IDEA 2020.3.1 (#46)

 

我遇到个类似，但是不一样点的问题


版本是1.5.6
已经做过

这个操作了

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
