### ISSUE TITLE
Can't set Project Root

### ISSUE THREAD

**Issue by azdanov** [xxpxxxxp/intellij-plugin-golangci-lint#49]
<img width="1109" alt="Screenshot 2021-01-13 at 08 19 33" src="https://user-images.githubusercontent.com/6123841/104414728-680cb880-5579-11eb-852e-7005c4b863af.png">

Project root is stuck in this directory. Even if I select a new one, and press apply/ok it is reset to the initial location. Is there a config location that I can manually edit?

**Comment by xxpxxxxp** [comment]
Yes, the config is at
`~/Library/Application Support/JetBrains/GoLand2020.3/options/other.xml`
Notice the space and version. Search for `go-custom-dir` and change the value

For the problem, are you selecting the folder back to the project's root?

**Comment by azdanov** [comment]
Yes, all the projects are inside `~/go/src/` and I want to switch to the current one. But it keeps reverting to another project.

**Comment by azdanov** [comment]
Okay, I solved it by removing this `<property name="go-custom-dir" value="$USER_HOME$/go/src/GoCasts" />` completely from global config file and now it selects proper root per project. No idea how it got stuck there...

Thank you.
