### ISSUE TITLE
Linter not running bucase it cannot load a package

### ISSUE THREAD

**Issue by bojan-embroker** [xxpxxxxp/intellij-plugin-golangci-lint#50]
Hi,

Linter won't run and Goland logs are showing the following error:

`go-linter - Run error: level=error msg="Running error: context loading failed: failed to load packages: cannot find package \".\" in:\n\t[REDACTED]: failed to analyze"`

It's also showing that it runs the command:

`go-linter - Debug command: cd <Goland project root folder> && ...`

Running that command in command line reproduces the above error and it can be fixed by changing it to:

` cd <folder I set in Go Linter settings as the root of Go source code> && ...`

**Comment by xxpxxxxp** [comment]
Hi @bojan-embroker , I may need more information to understand the question, such as
* The plugin panel screenshot
* The full debug command
* Goland project root folder path
* folder I set in Go Linter settings as the root of Go source code

Please do mask sensitive paths, I just need the relative path of `Goland project root folder path` and `folder I set in Go Linter settings as the root of Go source code`

**Comment by xxpxxxxp** [comment]
Hi @bojan-embroker , haven't heard from you for a couple of days, I'm closing this while please feel free to reopen it if necessary.
