### ISSUE TITLE
Plugin doesn't work in monorepo with multiple folders each with own go.mod

### ISSUE THREAD

**Issue by AdallomRoy** [xxpxxxxp/intellij-plugin-golangci-lint#51]
If you have a folder, let's say "project" with 2 sub-folders (project1, project2) each with its own go.mod, linter doesn't work, as it's trying to run golangci-lint in the root folder instead of in the project1/project2 folder according to the appropriate project.
This causes the following error: 

```
2021-01-19 15:48:50,827 [ 104171]   WARN -                      go-linter - Run error: level=error msg="Running error: context loading failed: no go files to analyze"
. Please make sure the project has no syntax error. 
```

**Comment by xxpxxxxp** [comment]
Hi @AdallomRoy , please consider using separate Goland instances to open those 2 sub-projects. As far as I know, Goland itself doesn't work well in such case, unless you have checked 'Index entire GOPATH' option. The option is not recommended to use with go mod, it also blocked go mod integration within Goland.

Also, another workaround is select `Project Root` to 1 of the sub-project in plugin settings, while in this case the plugin will only work for the selected sub-project.

**Comment by AdallomRoy** [comment]
Hi @xxpxxxxp, it's a repo with more than 90 projects, so I can't really open each project by itself.
Fortunately, GoLand does support it quite well, and I have worked with them to improve performance for that use-case.
Also, I'm pretty sure that in one of the previous versions of the plugin it worked quite well.
I don't think it's complicated to add logic that searches for the deepest folder with a go.mod file and run golangci-lint from the folder instead of only running it from the project root.

**Comment by xxpxxxxp** [comment]
Yeah, there was a refactoring to support #41 which will break this case. It would be easy to add an option to switch back the old way, if you aren't using the `exclude-rules` in config. Will included in next release.

**Comment by AdallomRoy** [comment]
Thanks!

**Comment by AdallomRoy** [comment]
Thanks for the new version, unfortunately, this is still not working for me.
I see that the command is still running "cd" to the root project directory and not to the project sub directory.
I have unchecked the "Project Root" setting.

**Comment by xxpxxxxp** [comment]
Sorry, I forgot to change to debug command, actually it's cd to the parent dir of the file.
For example, if the file path is `/root/sources/dev/hugo/hugolib/filesystems/basefs.go`, the plugin will cd to `/root/sources/dev/hugo/hugolib/filesystems` and run `golangci-lint run .` It's the old way month ago, only downside is not honoring `exclude-path` rules in config file.

**Comment by AdallomRoy** [comment]
Not quite sure what I changed in the config, but it started working :-) Thank you!

**Comment by xxpxxxxp** [comment]
Glad to known that!
