### ISSUE TITLE
Sub-projects and GoLand 2020.3.2

### ISSUE THREAD

**Issue by susuper** [xxpxxxxp/intellij-plugin-golangci-lint#54]
Hello.
I've got the same issue as #51 at GoLand 2020.3.2. Everything works fine at GoLand 2020.2.4, but doesn't work after upgrading to 2020.3.2. Go Linter is 1.4.10 and "Project root" is unchecked.

**Comment by xxpxxxxp** [comment]
Checking, seems Intellij Platform changed their way to load plugin, will follow up ASAP.

**Comment by susuper** [comment]
Looks like "Inspect code" feature is completely broken for multi-modules projects at GoLand 2020.3.2, I've created an issue at JetBrains tracker. Will inform here also about the results.

**Comment by xxpxxxxp** [comment]
Thanks a lot!

**Comment by xxpxxxxp** [comment]
I've checked the plugin should be working well now with the latest GoLand. Please feel free to reopen this issue if the problem persists.
