### ISSUE TITLE
What's the logic behind Suggest me! button?

### ISSUE THREAD

**Issue by frederikhors** [xxpxxxxp/intellij-plugin-golangci-lint#55]
I'm using your amazing plugin for a few minutes. What I don't understand is what is the logic behind `Suggest me!` button.

I'm on Windows. Does it change on Linux or Mac?

What's the logic?

Thanks for you amazing work!

**Comment by xxpxxxxp** [comment]
Thank you!

`Suggest me!` is simply a set of linters that's not error-prone (eg: scopelint), not too aggressive (eg: exhausive), not covered by GoLand itself (eg: errcheck). It's linters I'm using day-to-day (editor's choice!) and generally I'll fix. It's the same among all platforms.

The button is provided to unfamiliar users of `golangci-lint` as a quick start. Most users will move to their own `.golangci.yml` config soon.

**Comment by frederikhors** [comment]
> Most users will move to their own .golangci.yml config soon..

Done.
