### ISSUE TITLE
Can we have a button for enabled by default linters?

### ISSUE THREAD

**Issue by frederikhors** [xxpxxxxp/intellij-plugin-golangci-lint#56]
Can we have a button for https://golangci-lint.run/usage/linters/#enabled-by-default-linters?

**Comment by xxpxxxxp** [comment]
Hi @frederikhors , as mentioned in #55 , default linters are not suited for GoLand.
For example, GoLand has its own inspections like `deadcode, errcheck, unused, varcheck`.
Most users will move to their own `.golangci.yml` config soon, others will find their linters desired, so I would say the usage of such button is very limited.
