### ISSUE TITLE
Is there a way to save this plugin in project `.idea` dir?

### ISSUE THREAD

**Issue by frederikhors** [xxpxxxxp/intellij-plugin-golangci-lint#58]
Is there a way to save this plugin in project `.idea` dir?

Like VSCode recommended?

So everyone on the team can install it automagically?

**Comment by xxpxxxxp** [comment]
That's the `.golangci.yml` config file. Check it in within the project then everyone are using the same linter config.

Other settings like `golangci-lint` executable, project path, I guess team members should be allowed to have their own idea.

**Comment by frederikhors** [comment]
I mean something like this https://code.visualstudio.com/docs/editor/extension-gallery#_recommended-extensions.

Is there a way to suggest this plugin in new PCs?

**Comment by xxpxxxxp** [comment]
Yeah, Intellij has its own alternative: `Settings Repository`
Team members could use a git repo to make sure everyone has exactly the same plugin sets. It could also help syncing UI, code style, etc, between users.

**Comment by frederikhors** [comment]
It is too complicated compared to VSCode. Too bad.
