### ISSUE TITLE
A --fast flag?

### ISSUE THREAD

**Issue by frederikhors** [xxpxxxxp/intellij-plugin-golangci-lint#60]
For VSCode [this page](https://golangci-lint.run/usage/integrations/) says: 

> Using it in an editor without --fast can freeze your editor.

Is there something for this plugin in Goland?

My Goland _trembles_ every time I inspect the code.

**Comment by xxpxxxxp** [comment]
There's always a cost to run the linter, I'm trying best to minimize it, while it's inevitable.

`fast` flag only excludes `unused` linter which performs cross-module check, it can be easily set with a config file (https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml)
It's not in suggested linter set, while I can't blame if one really needs it. It's totally up to user's choice.
