### ISSUE TITLE
Something is wrong when run linter on "Whole project" inspection scope

### ISSUE THREAD

**Issue by pztrn** [xxpxxxxp/intellij-plugin-golangci-lint#63]
In my case it leads to showing no linting errors while actually there are some and will be shown if I try to start golangci-lint on specific file or if I start binary itself in terminal for whole project.

Unfortunately I cannot share code on which it occurs but I suspect any more-or-less big project with several packages can lead to that behavior.

**Comment by xxpxxxxp** [comment]
Hi @pztrn , if I'm understanding correctly, you are trying to run `Analyze - Inspect Code - Whole project`?
If that's the case, it's normal as the plugin is designed to run per file. Open a go file then related issues will be highlighted inline.

**Comment by xxpxxxxp** [comment]
Hi @pztrn , haven't heard from you for a long time, I'll close the issue, feel free to reopen it if necessary.
