### ISSUE TITLE
Get Latest - Failed to Get latest release

### ISSUE THREAD

**Issue by halleyshx** [xxpxxxxp/intellij-plugin-golangci-lint#65]
I can't get latest after installed, some error like this:
![image](https://user-images.githubusercontent.com/24284940/112108866-c3979a00-8beb-11eb-9517-827876218a0a.png)
null can not be cast to non-null type java.lang.String

**Comment by xxpxxxxp** [comment]
Hi @halleyshx , could I have your platform (Linux / Mac / Win, x64 / x86)? Also, does the issue repro every time?

**Comment by halleyshx** [comment]
@xxpxxxxp  my  platform is Mac x64(os version: 10.15.7);  the issue repro every time.

**Comment by xxpxxxxp** [comment]
Thanks, a few more questions to help me locate the problem:
* Please try `curl -L https://github.com/golangci/golangci-lint/releases/download/v1.38.0/golangci-lint-1.38.0-darwin-amd64.tar.gz -o golangci-lint-1.38.0-darwin-amd64.tar.gz` in terminal, to make sure it's not a network issue
* Have you seen any progress indicator after clicking the `Get Latest` button? If there is, what's the last message before it fails?

**Comment by xxpxxxxp** [comment]
Hi @halleyshx , haven't heard from you for a long time, I'll close the issue, feel free to reopen it if necessary.
