### ISSUE TITLE
Plugin is basically unusable on 2021.1

### ISSUE THREAD

**Issue by brakthehack** [xxpxxxxp/intellij-plugin-golangci-lint#66]
When typing, the plugin frequently hangs the UI for roughly half a second. This happens frequently enough (every few characters or so) that the UI freezes repeatedly and it's not possible to be productive at all.

When disabling the plugin, the UI and keystrokes become responsive again.

See my config below:
![Screen Shot 2021-04-16 at 10 36 36 AM](https://user-images.githubusercontent.com/2353650/115049228-19d0c380-9ea0-11eb-9bd9-aeba14d81a1c.png)

**Comment by xxpxxxxp** [comment]
Hi @brakthehack , I'm working on refactoring to boost perf, ETA release in 1 week.

**Comment by dmitry-ee** [comment]
+1 to this issue

**Comment by xxpxxxxp** [comment]
@brakthehack @dmitry-ee  Releasing fix tomorrow.

**Comment by xxpxxxxp** [comment]
Hi @brakthehack @dmitry-ee , I hope the hangs are somewhat relieved in the latest release, any feedback appreciated, thanks.

**Comment by xxpxxxxp** [comment]
Hi @brakthehack , I hope everything is going well on your side, I'm closing this issue now, please feel free to reopen it if perf is still unacceptable.
