### ISSUE TITLE
Please make sure there's no syntax error, then check if any config error

### ISSUE THREAD

**Issue by songkane** [xxpxxxxp/intellij-plugin-golangci-lint#70]
The log always shows as below
![image](https://user-images.githubusercontent.com/15307785/121806817-fe0d5200-cc83-11eb-9476-6cccebe67593.png)
![image](https://user-images.githubusercontent.com/15307785/121806866-390f8580-cc84-11eb-9ee2-0067ed304698.png)
![image](https://user-images.githubusercontent.com/15307785/121806886-4a589200-cc84-11eb-97f5-682ef99189ea.png)

It speed a lot time but I can't find how to fix it.
Can you help me about this error? Thank you

golangci.yaml

`
linters-settings:
  funlen:
    lines: 80
    statements: 80
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 20
  goimports:
  golint:
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  errcheck:
    check-type-assertions: true
  gocritic:
    enabled-checks:
      - nestingReduce
    settings:
      nestingReduce:
        bodyWidth: 5

linters:
  disable-all: true
  enable:
    - deadcode
    - funlen
    - goconst
    - gocyclo
    - gofmt
    - ineffassign
    - staticcheck
    - structcheck 
    - typecheck
    - goimports
    - golint
    - gosimple
    - govet
    - lll
    - rowserrcheck
    - errcheck
    - unused
    - varcheck
    - sqlclosecheck

run:
  timeout: 20m

issues:
  exclude-use-default: true
  include:
    - EXC0002 
    - EXC0003 
    - EXC0004 
    - EXC0005 
    - EXC0011

  exclude-rules:
    - path: _test\.go
      linters:
        - funlen 
    - linters:
        - staticcheck
      text: "SA1019: package github.com/golang/protobuf"
    - linters:
        - staticcheck
      text: "SA6002: argument should be pointer-like to avoid allocations"
    - linters:
        - structcheck
      text: "Store` is unused"
    - linters:
        - lll
      source: "^//go:generate "

  max-same-issues: 0
  new: false
  max-issues-per-linter: 0

output:
  sort-results: true

service:
  golangci-lint-version: 1.28.x
`

**Comment by xxpxxxxp** [comment]
Hi @songkane , please search for errors in goland log, you can find log via `Help` - `Show Log in XXX`
Search with word `go-linter`. There's more detailed debug infos around `Please make sure there's no syntax error, then check if any config error`, please attach the debug infos for further analysis.

**Comment by songkane** [comment]
![image](https://user-images.githubusercontent.com/15307785/121885160-66bd0300-cd46-11eb-8f6c-1e6027404638.png)
There are some errors I found
I fixed error : dial tcp 172.217.161.177:443: i/o timeout
But still have errors like ： 
Can't run linter goanalysis_metalinter: S1004
Can't run linter goanalysis_metalinter: S1016

And now, there is some highlight in some go files. But in some files, there are some errors, but not highlight

**Comment by xxpxxxxp** [comment]
Hi @songkane , could your project build successfully? From the errors, it seems there's package load issue, please run `go build` to verify packages valid.

**Comment by songkane** [comment]
Run go build is successful with no syntax error.  I checked the error files using golingci-lint run, it dose have some warnings, but Goland dose not highlight

**Comment by K4L1Ma** [comment]
![image](https://user-images.githubusercontent.com/6510147/122265110-a582c280-ced8-11eb-850c-9140064a4599.png)


In my case, changing back to go 1.15 made the error disappear completely

**Comment by xxpxxxxp** [comment]
Hi @songkane , please try execute the `Debug command` in terminal and see if there are errors. I bet it's a GOPATH issue.

**Comment by songkane** [comment]
There are some logs shows
`
2021-06-17 10:44:54,724 [349728814]   WARN -                      go-linter - Run error: level=warning msg="[runner] Can't run linter goanalysis_metalinter: S1000: failed prerequisites: [(inspect@git.xxxx.com/xxxx/workload, isgenerated@git.xxx.com/xxxx/workload): analysis skipped: errors in package: [/xxxx/workload/hpa.go:515:6: oldHPAReplicas declared but not used /xxxxx/workload/hpa.go:515:22: oldCronHPAReplicas declared but not used]]"
level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/xxxx/workload/hpa.go:515:6: oldHPAReplicas declared but not used /xxxxx/workload/hpa.go:515:22: oldCronHPAReplicas declared but not used]"
level=error msg="Running error: buildir: analysis skipped: errors in package: [/xxxxxx/workload/hpa.go:515:6: oldHPAReplicas declared but not used /xxxxxx/workload/hpa.go:515:22: oldCronHPAReplicas declared but not used]"
. Please make sure the project has no syntax error. 
`
However,  at line 515, I can't find any syntax error,  and no highlight at line 515:6 or 515:22,  The project still can be built  with "go build"
![image](https://user-images.githubusercontent.com/15307785/122323563-dfe07400-cf59-11eb-82a2-962cc92da959.png)

**Comment by songkane** [comment]
> ![image](https://user-images.githubusercontent.com/6510147/122265110-a582c280-ced8-11eb-850c-9140064a4599.png)
> 
> In my case, changing back to go 1.15 made the error disappear completely

My project still use go 1.14 because of some package depend

**Comment by songkane** [comment]
> There are some logs shows
> `2021-06-17 10:44:54,724 [349728814] WARN - go-linter - Run error: level=warning msg="[runner] Can't run linter goanalysis_metalinter: S1000: failed prerequisites: [(inspect@git.xxxx.com/xxxx/workload, isgenerated@git.xxx.com/xxxx/workload): analysis skipped: errors in package: [/xxxx/workload/hpa.go:515:6: oldHPAReplicas declared but not used /xxxxx/workload/hpa.go:515:22: oldCronHPAReplicas declared but not used]]" level=warning msg="[runner] Can't run linter unused: buildir: analysis skipped: errors in package: [/xxxx/workload/hpa.go:515:6: oldHPAReplicas declared but not used /xxxxx/workload/hpa.go:515:22: oldCronHPAReplicas declared but not used]" level=error msg="Running error: buildir: analysis skipped: errors in package: [/xxxxxx/workload/hpa.go:515:6: oldHPAReplicas declared but not used /xxxxxx/workload/hpa.go:515:22: oldCronHPAReplicas declared but not used]" . Please make sure the project has no syntax error. `
> However, at line 515, I can't find any syntax error, and no highlight at line 515:6 or 515:22, The project still can be built with "go build"
> ![image](https://user-images.githubusercontent.com/15307785/122323563-dfe07400-cf59-11eb-82a2-962cc92da959.png)

It is very weird. This file have no error. I fix some lint warning. Then plugin become working with no error

**Comment by xxpxxxxp** [comment]
Sorry for late reply, usually the plugin works well when the project could built. Please feel free to reopen this issue if it repros later.
