### ISSUE TITLE
Go Linter does not work with WSL

### ISSUE THREAD

**Issue by jaisingh** [xxpxxxxp/intellij-plugin-golangci-lint#71]
I get a go linter running error when using files access from WSL2 over the network share it exposes. The tool works fine for go projects on the windows filesystem.

**Comment by xxpxxxxp** [comment]
Thanks @jaisingh , I guess it's a path issue, will setup a WSL2 env ASAP to test it, might take a few days.

**Comment by xxpxxxxp** [comment]
Hi @jaisingh , I've done deep research, but sadly the plugin is not able to support WSL2 UNC path. It's actually limited by the go binary, related issues: https://github.com/golang/go/issues/37461 https://github.com/microsoft/WSL/issues/5762

In short, WSL2 is using 9P protocol to support file share between Linux and the host Windows. Problem is the 9P protocol doesn't support `LockFileEx` syscall and Go team refuses to support such case as Rust does. Mapping WSL2 to a driver would not help.

I'm closing this until WSL2 is supported by Go.
