### ISSUE TITLE
Please add support for aarch_64 (M1, ARM64)

### ISSUE THREAD

**Issue by garty09** [xxpxxxxp/intellij-plugin-golangci-lint#73]
<img width="426" alt="Снимок экрана 2021-07-10 в 14 24 14" src="https://user-images.githubusercontent.com/77111406/125161433-0bd2cc00-e18b-11eb-8d53-fa63df0d998e.png">

**Comment by xxpxxxxp** [comment]
Thanks @garty09 , will do soon.

**Comment by xxpxxxxp** [comment]
Thanks for confirming.
