### ISSUE TITLE
Go linter running error

### ISSUE THREAD

**Issue by YZerui** [xxpxxxxp/intellij-plugin-golangci-lint#74]
I can see only "Go linter running error, please make sure there's no syntax error, then check for any config error"，how can I do ？
![image](https://user-images.githubusercontent.com/10001503/125658932-fe0c3b9e-8d0a-441b-af0d-489df7fdc80f.png)

**Comment by xxpxxxxp** [comment]
Hi @YZerui , I hope your problem resolved. If any help needed please feel free to reopen this issue.

**Comment by y0rker** [comment]
@YZerui how u resolve problem?
