### ISSUE TITLE
Error plugin: Please make sure there's no syntax error, then check if any config error

### ISSUE THREAD

**Issue by y0rker** [xxpxxxxp/intellij-plugin-golangci-lint#75]
Hello! plugin doesn't work :(
My settings:
![image](https://user-images.githubusercontent.com/5592102/125964008-bba379f0-a6d4-4932-84b5-b7ebe3c1b1db.png)

And my golang ide version
![version](https://user-images.githubusercontent.com/5592102/125963600-219186b3-9c82-4fd2-b9cb-6af9332b807d.png)
Some debug message
`WARN -                      go-linter - Run error: level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: unsupported version of go: exit status 2: flag provided but not defined: -compiled\nusage: list [-e] [-f format] [-json] [build flags] [packages]\nRun 'go help list' for details.\n"
. Please make sure the project has no syntax error. `

My golang version: go version go1.17beta1 linux/amd64 . I try 1.15, 1.16 and 1.17...nothing work :(

if i write command in terminal
` /home/xxx/go/bin/golangci-lint run --disable=typecheck /home/xxx/go/src/my-app`
then working fine, but in golang ide i got error.

debug command:
`cd /home/xxx/go/src/my-app && export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/go/current/bin && export GOPATH= && '/home/xxx/go/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '3' '--max-issues-per-linter' '0' '--max-same-issues' '0' '--disable-all' '-E' 'govet,gosimple' 'dataproviders/facebook_api_providers'`

why GOPATH is empty? In IDE GOPATH completed

plz, help me!

**Comment by xxpxxxxp** [comment]
Hi @y0rker , please check your GOPATH setting inside Goland as below:

![image](https://user-images.githubusercontent.com/1585918/126024434-ebb862a8-4e2d-44b2-84e1-f6d479f17b94.png)

Please make sure at least 1 of Global or Project GOPATH exists, then try the plugin again.

**Comment by y0rker** [comment]
I'll check it out at work tomorrow. Thanks!

**Comment by y0rker** [comment]
In my case all okey.
![image](https://user-images.githubusercontent.com/5592102/126281633-4a793483-69e8-4700-bb7d-0e64dbc5542e.png)
This is right path

**Comment by xxpxxxxp** [comment]
Got it, so I guess you are using Linux? Let me test it later today.
Also, if the project you're working on is open-sourced, please share the git link, would be easier to debug with.

**Comment by y0rker** [comment]
Yes, Mint
![image](https://user-images.githubusercontent.com/5592102/126288741-9eab7dd4-0877-4507-a58c-aee696e4d823.png)
Sry, it is not open source and i cant share :(

**Comment by xxpxxxxp** [comment]
OK, so I've made a Linux Mint VM with Go 1.16, testing against https://github.com/gohugoio/hugo , the plugin works fine.
Would you please check Goland log again, see if GOPATH is still missing now?
I'm suspecting it's not a GOPATH issue. Does the `GOROOT` setting matches the go executable in terminal?

![image](https://user-images.githubusercontent.com/1585918/126328852-9073ed6d-664c-4493-840c-77426e63a61d.png)

**Comment by y0rker** [comment]
My goroot
![image](https://user-images.githubusercontent.com/5592102/126460578-0446ba87-7007-47e9-a161-0b7c23608ac7.png)
Maybe its bad permissions for golang ide?

> go-linter - Run error: level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: unsupported version of go: exit status 2: flag provided but not defined: -compiled\nusage: list [-e] [-f format] [-json] [build flags] [packages]\nRun 'go help list' for details.\n"
. Please make sure the project has no syntax error. 
2021-07-21 11:51:09,570 [436551702]   WARN -                      go-linter - Debug command: cd /home/xxx/go/src/ads-adapters/ads-adapter-facebook && export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/go/current/bin && export GOPATH=/home/xxx/go && '/home/xxx/go/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '3' '--max-issues-per-linter' '0' '--max-same-issues' '0' '--disable-all' '-E' 'staticcheck,interfacer,exportloopref,dupl,govet,funlen,errorlint,gocritic,goconst,gocognit,ineffassign,bodyclose,gosec,maligned,unconvert,revive,stylecheck,whitespace,goprintffuncname,gosimple,prealloc,gocyclo' '.' 

i checked all paths in this log.

**Comment by xxpxxxxp** [comment]
I see `GOPATH` is correct this time. Please execute the debug command in terminal, see if the same error shows.

1 more thing to be noted is that there are a lot paths in `PATH`. You might have different versions of `go` executable under those different paths. The actual `go` been used might be the one under `/usr/local/sbin` instead of `/snap/go/current/bin`, some of them could work while some don't.

**Comment by y0rker** [comment]
i found error.
if i call

> cd /home/xxx/go/src/ads-adapters/ads-adapter-facebook && export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/xxx/go/go1.16.6/bin && export GOPATH=/home/xxx/go/go1.16.6 && '/home/xxx/go/bin/golangci-lint' 'run' '-E' 'staticcheck'

then error. But if i move 

> /home/xxx/go/go1.16.6/bin

to start of PATH= like that

> cd /home/xxx/go/src/ads-adapters/ads-adapter-facebook && export PATH=/home/xxx/go/go1.16.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && export GOPATH=/home/xxx/go/go1.16.6 && '/home/xxx/go/bin/golangci-lint' 'run' '-E' 'staticcheck'

magic!
how can i fix it?

**Comment by xxpxxxxp** [comment]
Great! I think it is a real bug for me, as `GOROOT` set in IDE should always take precedence, I'll fix that soon.
For a workaround, you may reorder your system `PATH`, in `.bashrc` etc.

**Comment by y0rker** [comment]
Now working fine! Thanks!

**Comment by xxpxxxxp** [comment]
Thanks for confirming.
