### ISSUE TITLE
no go files to analyze

### ISSUE THREAD

**Issue by NSObjects** [xxpxxxxp/intellij-plugin-golangci-lint#78]
GoLand 2021.1.3
Build #GO-211.7442.57, built on June 9, 2021

golangci-lint has version v1.41.1 

Go Linter 1.5.3

![image](https://user-images.githubusercontent.com/17995427/127249180-113e7722-6434-4590-bc90-d6394987c6bc.png)

![image](https://user-images.githubusercontent.com/17995427/127249145-59f6f32b-ac98-49aa-a911-1280c1a159af.png)

**Comment by xxpxxxxp** [comment]
Hi @NSObjects , I'm afraid I didn't understand your question, those 2 screenshots don't seem related to the plugin? The plugin does not output anything, it does lint in editor.

And BTW the problem of the first screenshot is that the current running dir should be at
`/Users/mac/Documents/Code/Go/mxtio/jsm_live`

**Comment by sleyland** [comment]
I am also receiving this error, even after the latest plugin updates (running v1.5.4). This is the error output in the GoLand log file (NOTE: I've removed my username from the path and replaced with `<user>`):

```
2021-08-02 10:12:56,401 [1723930]  DEBUG - BackendServerFileEditorManager - Opening host editor for /Users/<user>/workspace/gocode/src/bitbucket.org/ffxblue/api-content/lib/api/asset.go 
2021-08-02 10:12:56,896 [1724425]   INFO - leTypes.UpdateComponentWatcher - updated: https://plugins.jetbrains.com/plugins/list?pluginId=org.jetbrains.plugins.go&build=GO-212.4746.93&pluginVersion=212.4746.93&os=Mac+OS+X+11.5.1&uuid=2807212b1b9dbca-8ede-4042-857e-6f9c17dcee14 
2021-08-02 10:12:57,921 [1725450]   WARN -                      go-linter - Run error: level=error msg="Running error: context loading failed: no go files to analyze"
. Please make sure the project has no syntax error. 
2021-08-02 10:12:57,929 [1725458]   WARN -                      go-linter - Debug command: cd /Users/<user>/workspace/gocode/src/bitbucket.org/ffxblue/api-content && export PATH=/usr/local/Cellar/go/1.16.6/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin && export GOPATH= && '/usr/local/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '3' '--max-issues-per-linter' '0' '--max-same-issues' '0' '-c' '/Users/<user>/workspace/docker-go-linter/config/golangci-lint/full/.golangci.yaml' 'lib/api' 
2021-08-02 10:13:03,339 [1730868]   INFO - System.impl.PopupMenuPreloader - Popup menu preloaded for `EditorPopup` in 15 ms
```

I am referencing a `golangci-lint.yaml` configuration file, however, removing that file as a configuration and replacing with the same selected linters also results in the same error.

I have tried the following:
* uninstall plugin
* reset IDE to 'default settings'
* reinstall plugin
* multiple configuration options

Setup:
MacOSX BigSur v11.5.1
Goland v2021.2
Golangci-lint plugin v1.5.4
Golangci-lint installed through Homebrew v1.41.1

**Comment by xxpxxxxp** [comment]
Hi @sleyland , from the `Debug command` in the log, it seems there's no `GOPATH` set in IDE
```
cd /Users/<user>/workspace/gocode/src/bitbucket.org/ffxblue/api-content
export PATH=/usr/local/Cellar/go/1.16.6/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin
export GOPATH=
'/usr/local/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '3' '--max-issues-per-linter' '0' '--max-same-issues' '0' '-c' '/Users/<user>/workspace/docker-go-linter/config/golangci-lint/full/.golangci.yaml' 'lib/api'
```

Please check your settings
![image](https://user-images.githubusercontent.com/1585918/127887916-7b14fd0d-5aea-4fa6-a46d-58905c3aabb3.png)

**Comment by sleyland** [comment]
Hi @xxpxxxxp 

I've rechecked the IDE settings and there is a globally configured `GOPATH`. See attached screenshot

<img width="995" alt="Screen Shot 2021-08-03 at 7 22 52 am" src="https://user-images.githubusercontent.com/23440051/127925773-050d2052-be40-41bb-88fc-32fd2dcd21a1.png">

**Comment by xxpxxxxp** [comment]
Thanks @sleyland for quick reply, would you try following commands in your terminal, with `GOPATH` already set to see if the command works
```
cd /Users/<user>/workspace/gocode/src/bitbucket.org/ffxblue/api-content
export PATH=/usr/local/Cellar/go/1.16.6/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin
'/usr/local/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '3' '--max-issues-per-linter' '0' '--max-same-issues' '0' '-c' '/Users/<user>/workspace/docker-go-linter/config/golangci-lint/full/.golangci.yaml' 'lib/api'
```

**Comment by sleyland** [comment]
Hi @xxpxxxxp,

Testing the command as you provided does work and provides prints a JSON style output to the terminal of all of the "issues" within the code. I did also get a warning with the output, but that seems more related to the linting configuration that is used in our projects.

```
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref.
```

Thus, since the command works in the terminal with the `$GOPATH` already defined, then I'm assuming that the issue is something inside the Goland/IntelliJ environment where despite the interface indicating that it has found the `$GOPATH` it doesn't seem to be provided to the plugin correctly?

Thanks,

**Comment by xxpxxxxp** [comment]
Hi @sleyland , seems the problem is the plugin failed to get `GOPATH` defined in IDE, a quick workaround would be add a `Project GOPATH`, let me review codes find out root cause.

**Comment by sleyland** [comment]
Hi @xxpxxxxp ,

Apologies for not getting back to you sooner, but I've just added the appropriate `Project GOPATH` and it still causes the plugin to fail. I have also tried copying and pasting that command into the terminal and it produces the same result.

```
ERROR Running error: context loading failed: no go files to analyze
```

This is the command which is logged by Goland/IntelliJ

```
cd /Users/sleyland/workspace/gocode/src/bitbucket.org/ffxblue/api-front-internal && export PATH=/usr/local/Cellar/go/1.16.6/libexec/bin:/usr/bin:/bin:/usr/sbin:/sbin && export GOPATH=/Users/sleyland/workspace/gocode && '/usr/local/bin/golangci-lint' 'run' '--out-format' 'json' '--allow-parallel-runners' '-j' '3' '--max-issues-per-linter' '0' '--max-same-issues' '0' '-c' '/Users/sleyland/workspace/docker-go-linter/config/golangci-lint/full/.golangci.yaml' 'pkg/schema/asset'
```

Admittedly I've tried this in a different repository to the one I originally posted about. However, going back to that repository and adding in the appropriate configuration (i.e. the `Project GOPATH`) means that I no longer get errors output to the visible `error log` in the editor. However, when I examine the log, I can still see that it complains that it about having no go files to analyze.

**Comment by xxpxxxxp** [comment]
Hi @sleyland , that was surprising, the plugin is running the exact command inside. I guess there are some env variable differences between the IDE and the terminal. Please run the exact commands in the IDE terminal (`View` - `Tool Windows` - `Terminal`) see if it works for the IDE env.

**Comment by sleyland** [comment]
Hi @xxpxxxxp ,

The command also works inside the `terminal` within Goland/IntelliJ. The process I went through was:

- opened a `.go` file in the editor
- checked the `event log` to see that there was a configuration error with the plugin (there was)
- opened the `idea.log` to grab the command that was executed
- copy/paste the command from the `idea.log` into a `terminal` within Goland/IntelliJ
- command output an appropriate response

So as you mentioned, it is likely that there is some environment variable difference between how it executes inside the IDE and then in the terminal.

Thanks,

**Comment by xxpxxxxp** [comment]
Hi @sleyland , I'm trying to reproduce the issue you are facing, since you are working on a non-open-source project, any chance you can try the plugin with an open-source project, eg: https://github.com/gin-gonic/gin codebase is smaller enough to clone and build in minutes, see if the plugin works.

**Comment by sleyland** [comment]
Hi @xxpxxxxp ,

Seemingly everything is working fine with that project in Goland/IntelliJ. I can see various highlighted warnings inside the code editor when using "my" linting configuration. I also checked the `ide.log` and couldn't see any issues being reported by the tool.

Thanks for looking into this, and apologies that the code I'm working on isn't open-source (making life difficult)
