### ISSUE TITLE
no go files to analyze

### ISSUE THREAD

**Issue by xxpxxxxp** [xxpxxxxp/intellij-plugin-golangci-lint#81]
Hi @xxpxxxxp ,

Seemingly everything is working fine with that project in Goland/IntelliJ. I can see various highlighted warnings inside the code editor when using "my" linting configuration. I also checked the `ide.log` and couldn't see any issues being reported by the tool.

Thanks for looking into this, and apologies that the code I'm working on isn't open-source (making life difficult)

_Originally posted by @sleyland in https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/issues/78#issuecomment-896315071_

**Comment by xxpxxxxp** [comment]
@sleyland

**Comment by xxpxxxxp** [comment]
Hi @sleyland , I'm having a picture of what happened. I guess you are not using `go mod` to manage project dependency, it's a Goland base project, is that right?

**Comment by sleyland** [comment]
Hi @xxpxxxxp ,

The project that I mentioned the original issue with is configured to use `dep` which we know is _deprecated_ in favour of `go mod`, so are in the process of moving it over, but that hasn't happened yet.

I have done a test in some of our other repos which do you `go mod` and I can confirm that the plugin works. **Only** if I update the `GOPATH` setting in the IDE to have a `Project GOPATH` (as we had previously discussed https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/issues/78#issuecomment-891128495).

Hope that provides some missing context.

**Comment by xxpxxxxp** [comment]
Thank you, I guess that's the cause, the plugin doesn't work with `dep` now. Let me found a workaround in a few weeks.

**Comment by talos-rob** [comment]
For me the issue was here:  https://github.com/golangci/golangci-lint/issues/825#issuecomment-630004446

You have to run from a working directory holding go.mod.  My Goland project root is not the go code root, so go.mod is in a subdirectory
