### ISSUE TITLE
Default .golangci.yaml ?

### ISSUE THREAD

**Issue by SimpleFelix** [xxpxxxxp/intellij-plugin-golangci-lint#82]
How can I export a .golangci.yaml from "Tools"-"Go Linter" after having checked and unchecked a few linters?
Where is the default configuration file?

**Comment by SimpleFelix** [comment]
I'm using GoLand 2021.2 on Win10 by the way.

**Comment by xxpxxxxp** [comment]
For linters selected inside IDE, the plugin does not use a configuration file. Thus, no way to export a config file, sorry for that.
Meanwhile it's quite easy to work out such a config file all by yourself, checkout https://golangci-lint.run/usage/configuration/#config-file

**Comment by SimpleFelix** [comment]
Thanks for the answering.
I still think it will be cool if you add an Export button inside IDE though.
