### ISSUE TITLE
some folder no more warnings in Goland 2021.2

### ISSUE THREAD

**Issue by Naist4869** [xxpxxxxp/intellij-plugin-golangci-lint#84]
# 大佬你好
go-linter 解决了冻结ide问题后非常好用 但是我的电脑上可能由于配置环境出现了部分情况不工作的问题

## 探索发现
- 在项目中有些文件夹没有警告
![image](https://user-images.githubusercontent.com/37408934/129042677-97050e06-aa9b-445b-bf1c-3609219a7de7.png)
![image](https://user-images.githubusercontent.com/37408934/129042756-835dd92d-baba-49a8-9701-124fb940a7e3.png)
- 在同一个项目中有些文件夹有警告
![image](https://user-images.githubusercontent.com/37408934/129042986-876f5161-5e34-485b-a7b1-0f6b1d9cae20.png)
- 我以为是警告太多没有显示出来, 可是在我另一个错误很多的文件夹也有警告
![image](https://user-images.githubusercontent.com/37408934/129043652-4a4f6be9-2665-498f-8e07-dd13234f47c0.png)
![image](https://user-images.githubusercontent.com/37408934/129043963-068e0881-6342-48e6-842b-6a646db3b980.png)
- 然后又发现了有些ci报的错go-linter没有警告
![image](https://user-images.githubusercontent.com/37408934/129044721-d3b99476-d67e-41b8-b584-ae3e00627775.png)
![image](https://user-images.githubusercontent.com/37408934/129044907-c5bb9dad-524a-49e9-a2ce-bc1b38c85644.png)
- 我以为是.golangci的问题 把文件拷贝到gin目录下发现正常工作
![image](https://user-images.githubusercontent.com/37408934/129045454-69d1fdb7-1478-41cd-9e1b-010f125ef0ca.png)
- 别的尝试
![image](https://user-images.githubusercontent.com/37408934/129045919-2c939335-3bf9-4f2a-bd08-a5a73c17889d.png)
![image](https://user-images.githubusercontent.com/37408934/129046003-89fbd738-3063-420d-a371-d07571649654.png)
![image](https://user-images.githubusercontent.com/37408934/129046259-4605e792-6501-4151-9ea1-7b9aaf173e1d.png)
![image](https://user-images.githubusercontent.com/37408934/129047089-99995a6a-0e33-43ab-b61a-fe7c80d083ba.png)

## log文件
[idea.log](https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/files/6969117/idea.log)

整了一下午没搞定 求大佬帮忙debug

**Comment by xxpxxxxp** [comment]
感谢，对于那些没有报错误的文件，试一下 `Code` - `Inspect Code` - Scope选到 `File`，看看能不能正常出lint。Plugin不使用IDE缓存，清理缓存没什么用。

**Comment by Naist4869** [comment]
> 感谢，对于那些没有报错误的文件，试一下 `Code` - `Inspect Code` - Scope选到 `File`，看看能不能正常出lint。Plugin不使用IDE缓存，清理缓存没什么用。
噢噢 之前看有人这样做搞定了  [#42](https://github.com/xxpxxxxp/intellij-plugin-golangci-lint/issues/42)


- 使用新方法之后,没什么反应,这两个文件ci都报了很多
![image](https://user-images.githubusercontent.com/37408934/129159685-37257c70-44d8-49d5-8217-c1ae97a133b2.png)
![image](https://user-images.githubusercontent.com/37408934/129159290-7ad48b51-bdb6-4337-ba78-ceab232fb04b.png)

**Comment by xxpxxxxp** [comment]
感谢，从目前的信息上我难以重现这个问题，能不能摘取一些非机密的code独立成一个能复现的go mod project给我看看？

**Comment by Naist4869** [comment]
> 感谢，从目前的信息上我难以重现这个问题，能不能摘取一些非机密的code独立成一个能复现的go mod project给我看看？

当然可以 [go-linter-84](https://github.com/Naist4869/go-linter-84) .idea文件夹也push上去了

**Comment by xxpxxxxp** [comment]
发现问题是code中的中文，比如这种 string `"目标服务器什么都没返回"`，golangci-lint返回的结果乱码导致json解析失败，看起来是编码的问题，我看看怎么修一下

**Comment by Naist4869** [comment]
> 发现问题是code中的中文，比如这种 string `"目标服务器什么都没返回"`，golangci-lint返回的结果乱码导致json解析失败，看起来是编码的问题，我看看怎么修一下

果然 按照命令行先把带中文的修复了 ide就有警告出现了 这问题只出现在windows上  同事的mac没有这问题 
感谢大佬 项目也不贴个二维码 想请大佬喝茶

**Comment by xxpxxxxp** [comment]
看起来是`golangci-lint`在windows上读入文件时候encoding就错了，我看看code给他们提个PR吧

**Comment by xxpxxxxp** [comment]
感谢使用，这周内准备发一版修好这个问题。

**Comment by xxpxxxxp** [comment]
新版本发布了，麻烦确认下这个问题有没有修好，感谢

**Comment by heyanlong** [comment]
How to upgrade to this version

**Comment by Naist4869** [comment]
已确认修复
