### ISSUE TITLE
wrapcheck linting even though error is wrapped

### ISSUE THREAD

**Issue by MaxBreida** [xxpxxxxp/intellij-plugin-golangci-lint#87]
Even though I wrap an error using [github.com/pkg/errors](https://github.com/pkg/errors), I still get linter warnings from wrapcheck linter:

![image](https://user-images.githubusercontent.com/18685579/139292527-d2b80da9-31f4-4b48-9e4e-88c29c986b74.png)

Using Intellij 2021.2.3 Ultimate Edition with Go Plugin
Go Linter Version 1.5.5

**Comment by xxpxxxxp** [comment]
Hi @MaxBreida , there are 2 possible causes:

1. You have a config file (`.golangci.yml`) explicitly leave out `.Wrap(` of `wrapcheck` linter (see https://golangci-lint.run/usage/configuration/)

2. It's the plugin's cache, just save the file and wait for seconds, the message will gone away.

**Comment by MaxBreida** [comment]
Hey, thanks for your answer. Neither your suggestions, nor updating golangci did help. Completely re-installing golangci did the trick though, so I'll close this issue.
