### ISSUE TITLE
How do you run it once installed?

### ISSUE THREAD

**Issue by platypusguy** [xxpxxxxp/intellij-plugin-golangci-lint#90]
I have it installed, but cannot find anywhere in Goland a way to run the linter. It does not appear under Tools->Go Tools nor, in fact, under the Tools menu at all. Nor can I find it anywhere else. What's the answer?

Whatever the way to run it from inside Goland is, I think it would be useful to include it in these instructions.

**Comment by xxpxxxxp** [comment]
Hi @platypusguy , please double-check the plugin is installed and enabled:
![image](https://user-images.githubusercontent.com/1585918/141766628-683f60c9-30a2-41f5-a122-390bca6cfc73.png)

The plugin comes with a wizard, once installed it will popup at the bottom-right corner, just select or download a linter then everything should be fine.

**Comment by platypusguy** [comment]
It's definitely installed. I'd like to run it manually from Goland, but cannot find it in any menu nor any button. How do I do that?

**Comment by xxpxxxxp** [comment]
Well, after the plugin is installed, please make sure a valid `golangci-lint` executable selected, then select linters as you wish
![image](https://user-images.githubusercontent.com/1585918/142241722-005cc74a-e253-40ef-b5aa-5e106ab547e8.png)

The plugin is running on-the-fly and display hints inline
![image](https://user-images.githubusercontent.com/1585918/142242240-e93be1ad-a679-4db3-bbb8-5d01eec5e102.png)

If you'd like to manually trigger a run, please click on menu `Code` - `Inspect Code`, select any scope then run it, hints will be show at `Problem` tab
![image](https://user-images.githubusercontent.com/1585918/142242650-1e96ecfa-b5a4-4368-a91c-a69749025e05.png)

**Comment by platypusguy** [comment]
Thank you. That's very helpful. I'd suggest adding this info to the instructions. Thanks again!
