### ISSUE TITLE
//nolint based supression of IDE warnings

### ISSUE THREAD

**Issue by codefromthecrypt** [xxpxxxxp/intellij-plugin-golangci-lint#92]
Goland adds "Unhandled Error" warnings even when `//nolint` is added.

Ex even if I have this plugin installed and do this:
```
	moreos.Fprintf(o.Out, format, a...) //nolint
```

where there are returns, the comment is ignored and the IDE generates warnings.

A few teammates and I ran into this in other projects and found https://youtrack.jetbrains.com/issue/GO-6502 Since this was marked "won't fix" by @zolotov a few years ago it is impossible to upvote the issue, though I suspect many would have wanted to. Until jetbrains accepts golangci projects as de-facto enough to consider conventions, I think this is the only existing project that could handle this.

Is it possible to remove IDE generated warnings based on `//nolint` comments? If so, could you add this to the project?

**Comment by xxpxxxxp** [comment]
Hi @codefromthecrypt , I'm afraid I'm not able to help in your case, this plugin adds `golangci-lint` hints, but doesn't have control on IDE generated hints. `golangci-lint` honors `//nolint` comment, IDE doesn't. I cannot think of a better way than to upvote https://youtrack.jetbrains.com/issue/GO-6502 . Or maybe commit a PR to fix all those hints in one time.

**Comment by codefromthecrypt** [comment]
sadly as the upstream issue is marked "won't fix" there's no way to upvote
it. It is a pity people will end up committing tech debt over this.. Anyway
thanks for looking into it here, and I appreciate there is nothing you can
do. We have to hope someone at jetbrains will unlock that issue.
