### ISSUE TITLE
GOROOT not set error, no linters

### ISSUE THREAD

**Issue by iangregsondev** [xxpxxxxp/intellij-plugin-golangci-lint#93]
Hi,

Strange error, rebooted but still the same, GOROOT is set, but I set it again and still constantly it shows the error with no linters available.

![image](https://user-images.githubusercontent.com/2370364/144719875-20cd87ad-47b3-46d1-b917-3a9d25672baf.png)

go version go1.17 darwin/amd64

golangci-lint has version 1.43.0 built from 861262b on 2021-11-02T20:54:42Z

![image](https://user-images.githubusercontent.com/2370364/144719926-0bc20017-f956-427f-84a7-441327c5552f.png)

**Comment by xxpxxxxp** [comment]
Hi @iangregsondev , the `GOROOT` referring here isn't the one in bash, it's the one in IDE, please make sure there's a valid GO SDK selected.
![image](https://user-images.githubusercontent.com/1585918/144777859-42e8ba8c-7bfc-468e-b49a-cd744a7559b0.png)

**Comment by xxpxxxxp** [comment]
And if you have recently updated Go by `brew` or something similar, please restart IDE to let the new `GOROOT` take effect.

**Comment by iangregsondev** [comment]
Thanks, this was a weird one. I think it was an invalid yaml file...

I removed the yaml config and then it worked and re-added it and now it works again

thanks for your prompt support.
