### ISSUE TITLE
Not work in WSL2

### ISSUE THREAD

**Issue by DeniskaAbr** [xxpxxxxp/intellij-plugin-golangci-lint#95]

**Comment by xxpxxxxp** [comment]
Hi @DeniskaAbr , I've tried but the thing is `golangci-lint` itself cannot work with WSL2. Case-by-case saying:
* `golangci-lint` and code both inside WSL2, this way the linter works, but can't be integrated with Goland
* `golangci-lint` in Windows and code inside WSL2, this way it can be integrated with Goland, but don't work with code

By any chance if you make the 2nd way works, please let me know.
