### ISSUE TITLE
import a package but remind me not used and lint about "typecheck"

### ISSUE THREAD

**Issue by txt1999** [xxpxxxxp/intellij-plugin-golangci-lint#98]
when i import a package such as "xxx/v2", and then 
`var a = xxx.New()`
the linter always remind 
`"xxx/v2" imported but not used (typecheck)`

**Comment by txt1999** [comment]
> 

i'm sure that my code could successfully built and it's running so happy
![image](https://user-images.githubusercontent.com/28136545/149082464-083ef8f9-6f3d-4d75-a83e-b4a1bfbb261c.png)

**Comment by xxpxxxxp** [comment]
Hi @txt1999 , please try run `go mod tidy` on your project, then inspect the file again.

**Comment by xxpxxxxp** [comment]
Haven't heard from you for a month, closed for now. Feel free to reopen.
