### ISSUE TITLE
go-linter 报告配置错误【已解决】

### ISSUE THREAD

**Issue by workwb** [xxpxxxxp/intellij-plugin-golangci-lint#99]
`Go linter running error: 
			Please make sure there's no syntax error, then check if any config error`

对于这个问题，需要注意一下，我目前认为出现错误的情况是因为 go mod 依赖没有拉取好，或者就是没有拉。

只需要要在项目中执行 ` go mod tidy ` 之后 该插件会正常运行！

**Comment by workwb** [comment]
希望可以提供一些注意事项，或者可能的错误处理方式，并统一展示

**Comment by xxpxxxxp** [comment]
嗯好的，报错的时候可以提示一下。
